import "./ditto.css";
import Footer from "../sections/footer";
import Navbar from "../sections/navbar";
import DittoWire from "../ditto/DittoWire";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import ListRow3 from "./components/list-row3";
import ListRow4 from "./components/list-row4";
import ListRow5 from "./components/list-row5";
import ListRow6 from "./components/list-row6";
import ListRow7 from "./components/list-row7";
import ListRow8 from "./components/list-row8";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { href: "/formations/expert-ia", label: "Expert IA" },
    { href: "/formations/automatisation-n8n", label: "Automatisation & n8n" },
    { href: "/formations/robotique", label: "Robotique" },
    { href: "/formations/ia-recherche-sciences", label: "IA, Recherche & Sciences" }
];
const ListRow2_data = [
    { href: "/entreprises", label: "Entreprises" },
    { href: "/actualites", label: "Actualités" },
    { href: "/contact", label: "Contact" }
];
const ListRow3_data = [
    { href: "/entreprises", label: "Entreprises" },
    { href: "/actualites", label: "Actualités" },
    { href: "/contact", label: "Contact" }
];
const ListRow4_data = [
    { href: "/entreprises", label: "Entreprises" },
    { href: "/actualites", label: "Actualités" },
    { href: "/contact", label: "Contact" }
];
const ListRow_data2 = [
    { href: "/formations/expert-ia", label: "Expert IA" },
    { href: "/formations/automatisation-n8n", label: "Automatisation & n8n" },
    { href: "/formations/robotique", label: "Robotique" },
    { href: "/formations/ia-recherche-sciences", label: "IA, Recherche & Sciences" }
];
const ListRow5_data = [
    { href: "/entreprises", label: "Entreprises" }
];
const ListRow6_data = [
    { href: "https://wa.me/243792369704", label: "WHATSAPP" },
    { href: "mailto:info@hoja-academy.com", label: "LINKEDIN" },
    { href: "https://hojanetwork.org", label: "HOJA NETWORK" },
    { href: "https://hojanetwork.org", label: "HOJA NETWORK" }
];
const ListRow7_data = [
    { href: "/confidentialite", label: "Politique de Confidentialité & Conditions" },
    { href: "/cookies", label: "Politique des Cookies" },
    { href: "/mentions-legales", ariacurrent: "page", label: "Mentions Légales" },
    { href: "/accessibilite", label: "Accessibilité" },
    { href: "/entreprises", label: "Entreprises" }
];
const ListRow8_data = [
    { href: "/confidentialite", label: "Politique de Confidentialité & Conditions" },
    { href: "/cookies", label: "Politique des Cookies" },
    { href: "/mentions-legales", ariacurrent: "page", label: "Mentions Légales" },
    { href: "/accessibilite", label: "Accessibilité" },
    { href: "/entreprises", label: "Entreprises" }
];
const ListRow_meta: string[][] = [
    ["interaction-sm-1767225603097025-2", "n22"],
    ["n23", "n24"],
    ["n25", "style-wp-submit"],
    ["n27", "n28"]
];
const ListRow2_meta: string[][] = [
    ["n29", "style-div"],
    ["style-div-18", "style-div-2"],
    ["style-div-19", "style-div-3"]
];
const ListRow3_meta: string[][] = [
    ["n56", "n57"],
    ["n58", "n59"],
    ["n60", "n61"]
];
const ListRow4_meta: string[][] = [
    ["n79", "n80"],
    ["n81", "n82"],
    ["n83", "n84"]
];
const ListRow_meta2: string[][] = [
    ["interaction-p-3", "interaction-button"],
    ["interaction-span-3", "style-p"],
    ["interaction-link", "interaction-span-4"],
    ["style-navegaci-n-entre-noticias-del-d-a", "style-link-7"]
];
const ListRow5_meta: string[][] = [
    ["style-br-3", "n147"],
    ["n148", "n149"],
    ["n150", "style-br-2"]
];
const ListRow6_meta: string[][] = [
    ["interaction-div-7", "n165", "interaction-div-6"],
    ["interaction-div-8", "style-menu-2", "interaction-menu-1-516d334"],
    ["n170", "style-link-32", "interaction-li-2"],
    ["interaction-sm-17672256027865476-1", "style-span-6", "style-icon-2"]
];
const ListRow7_meta: string[][] = [
    ["style-div-10", "style-div-94"],
    ["n202", "n203"],
    ["interaction-b", "n205"],
    ["style-b-2", "interaction-li"],
    ["style-b-6", "style-li-5"]
];
const ListRow8_meta: string[][] = [
    ["style-footer", "style-div-95"],
    ["n216", "interaction-div-2"],
    ["style-link-2", "style-span-2"],
    ["interaction-span-2", "style-icon-3"],
    ["style-span-46", "n223"]
];
const ListRow_styles = [
    { className: "rounded-tl-[25px] rounded-tr-[25px]" },
    {  },
    {  },
    { className: "rounded-br-[25px] rounded-bl-[25px]" }
,
    { className: "" }];
const ListRow2_styles = [
    { className: "mx-[0.5px] 2xl:mx-[9.5px] after:right-[6.5625rem] 2xl:after:right-29.5" },
    { className: "mx-[0.5px] 2xl:mx-[9.5px] after:right-[6.0625rem] 2xl:after:right-[6.9375rem]" },
    { className: "ml-[0.5px] 2xl:ml-[9.5px] after:right-[5.0625rem] 2xl:after:right-[5.8125rem]" }
,
    { className: "" },
    { className: "" }];
const ListRow3_styles = [
    {  },
    {  },
    { className: "max-lg:rounded-br-[10px] max-lg:rounded-bl-[10px]" }
,
    { className: "" },
    { className: "" }];
const ListRow4_styles = [
    { className: "mx-[0.5px] 2xl:mx-[9.5px] after:right-[6.5625rem] 2xl:after:right-29.5" },
    { className: "mx-[0.5px] 2xl:mx-[9.5px] after:right-[6.0625rem] 2xl:after:right-[6.9375rem]" },
    { className: "ml-[0.5px] 2xl:ml-[9.5px] after:right-[5.0625rem] 2xl:after:right-[5.8125rem]" }
,
    { className: "" },
    { className: "" }];
const ListRow_styles2 = [
    { className: "rounded-tl-[15px] rounded-tr-[15px]" },
    {  },
    {  },
    { className: "rounded-br-[15px] rounded-bl-[15px]" }
,
    { className: "" }];
const ListRow5_styles = [
    { className: "mx-[17.5px] max-md:mx-[0.5625rem] 2xl:mx-[21.5px]" },
    { className: "mx-[17.5px] max-md:mx-[0.5625rem] 2xl:mx-[21.5px]" },
    { className: "ml-[17.5px] max-md:ml-[0.5625rem] 2xl:ml-[21.5px]" }
,
    { className: "" },
    { className: "" }];
const ListRow7_styles = [
    { className: "mr-[8.5px] 2xl:mr-[9.5px]" },
    { className: "mx-[8.5px] 2xl:mx-[9.5px]" },
    { className: "mx-[8.5px] 2xl:mx-[9.5px]" },
    { className: "mx-[8.5px] 2xl:mx-[9.5px]" },
    { className: "ml-[8.5px] 2xl:ml-[9.5px]" }
];
const ListRow8_styles = [
    { className: "mr-[8.5px] max-md:mr-[0.4375rem]" },
    { className: "mx-[8.5px] max-md:mx-[0.4375rem]" },
    { className: "mx-[8.5px] max-md:mx-[0.4375rem]" },
    { className: "mx-[8.5px] max-md:mx-[0.4375rem]" },
    { className: "ml-[8.5px] max-md:ml-[0.4375rem]" }
];

export const metadata = {
  title: 'Mentions légales | HOJA ACADEMY',
  description: 'Informations légales relatives au site hoja-academy.com.',
};
export default function Page() {
  return (
    <>
      {" "}
      <a className="w-px h-px block absolute -top-37500 left-0 -m-px overflow-hidden text-color-001 [font-family:Montserrat,_sans-serif] text-[0.9375rem] font-medium leading-[1.1875rem] [clip-path:inset(50%)] coursr-pointer" href="#content">
        Aller au contenu
      </a>
      {" "}
      <Navbar />
      {" "}
      <main className="block" id="content">
        {" "}
        <div className="block">
          <div className="block">
            <div className="min-h-[25.3125rem] flex relative max-w-full -mt-[7.0625rem] justify-center items-center gap-5 bg-color-001 bg-cover [background-position:50%_50%] bg-no-repeat max-md:min-h-[15.0625rem] max-md:-mt-22.5 max-md:px-[0.9375rem] max-md:flex-wrap max-md:justify-end md:max-lg:px-[3.3125rem] 2xl:-mt-33 2xl:pl-[13.8125rem]" style={{ backgroundImage: "url(\"/assets/cloned/images/6bfaf6f6a88b.png\")" }}>
              <div className="w-240 min-h-[16.3125rem] flex relative min-w-0 flex-col justify-end gap-5 max-md:w-[21.5625rem] max-md:min-h-41 max-md:flex-wrap md:max-lg:w-[569.3px] 2xl:w-[106.1875rem] 2xl:p-2.5">
                <div className="block relative min-w-0 max-w-full gap-5">
                  <div className="block">
                    <h1 className="block text-primary [font-family:Montserrat,_sans-serif] text-[2.625rem] font-bold leading-[6.3125rem] max-md:text-3xl max-md:leading-9" data-ditto-id="style-span-39" data-component="heading">Mentions Légales</h1>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
            <div className="min-h-[44.8125rem] flex relative max-w-full py-16 px-[3.2rem] justify-center gap-5 max-md:pt-10 max-md:pb-5 max-md:px-5 max-md:flex-wrap md:max-lg:py-[2.4rem] md:max-lg:px-[30.7px] 2xl:py-24 2xl:px-[4.8rem]" data-ditto-id="style-section">
              <div className="w-4/5 block relative min-w-0 max-w-full gap-5 text-color-001 max-md:text-base max-md:leading-[1.3125rem]" data-ditto-id="style-div-83">
                <div className="h-full block" data-ditto-id="style-p-10">
                  <p className="block mb-[0.9rem]" data-ditto-id="style-heading-4">
                    <strong className="inline font-bold" data-ditto-id="style-div-84">
                      HOJA ACADEMY
                    </strong>
                    {" Les informations suivantes sont fournies conformément à la législation applicable sur le commerce électronique :"}
                    <br className="inline" data-ditto-id="style-span-40" />
                    {"Qu'il est titulaire du domaine et du site web : "}
                    <a className="inline [font-family:Montserrat,_sans-serif] text-[0.9375rem] font-medium leading-[1.1875rem] coursr-pointer" data-component="link" href="/">
                      https://hoja-academy.com/
                    </a>
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="interaction-span-11">
                    <b className="inline font-bold">
                      Que ses données d'identification sont :
                    </b>
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-section-2">
                    HOJA ACADEMY
                    <br className="inline" data-ditto-id="interaction-div-26" />
                    —
                    <br className="inline" />
                    Contact : info@hoja-academy.com
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]">
                    L'utilisation du site web confère la qualité d'utilisateur et implique l'acceptation pleine et entière de toutes les dispositions du présent Avis Légal et de la Politique de Confidentialité. Si l'utilisateur n'est pas d'accord avec les conditions établies ici, il doit renoncer à accéder au site web et à l'utiliser.
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-p-6">
                    {"Le contenu du site web est la propriété de "}
                    <strong className="inline font-bold">
                      HOJA ACADEMY
                    </strong>
                    , et il est interdit de procéder à quelque copie ou reproduction que ce soit, de tout ou partie du contenu, sans l'autorisation expresse de son propriétaire.
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-p-13">
                    {"L'utilisateur du site web s'engage à en faire un usage approprié, à ne pas l'employer à des pratiques contraires à la Loi ou à la bonne foi et à ne pas causer de dommages aux systèmes physiques et logiques de "}
                    <strong className="inline font-bold" data-ditto-id="style-p-7">
                      HOJA ACADEMY
                    </strong>
                  </p>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </main>
      {" "}
      <Footer />
      {" "}
      <span className="w-1 h-1 border-2 border-inset border-foreground block absolute -top-[624.9375rem] overflow-clip" data-ditto-id="style-image" aria-hidden="true" role="presentation" title="Vidéo témoignage — apprenant HOJA ACADEMY"></span>
      {" "}
      <svg className="hidden overflow-hidden" fill="currentColor" />
      {" "}
          </>
  );
}
