import "./ditto.css";
import Footer from "../sections/footer";
import Navbar from "../sections/navbar";
import DittoWire from "../ditto/DittoWire";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import ListRow3 from "./components/list-row3";
import ListRow4 from "./components/list-row4";
import ListRow5 from "./components/list-row5";
import ListRow6 from "./components/list-row6";
import FeatureCard from "./components/feature-card";
import ListRow7 from "./components/list-row7";
import ListRow8 from "./components/list-row8";
import ListRow9 from "./components/list-row9";
import ListRow10 from "./components/list-row10";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { href: "/formations/expert-ia", label: "Expert IA" },
    { href: "/formations/automatisation-n8n", label: "Automatisation & n8n" },
    { href: "/formations/robotique", label: "Robotique" },
    { href: "/formations/ia-recherche-sciences", label: "IA, Recherche & Sciences" }
];



const ListRow5_data = [
    { text: " 16 séances en direct, 8 semaines, 18 modules" },
    { text: "Application à vos processus réels dès la première semaine" },
    { text: "AI Work Kit et soutenance finale" }
];
const ListRow5_data2 = [
    { text: "Diagnostic préalable de vos usages et de vos processus" },
    { text: "Contenus, durée et format ajustés à vos équipes" },
    { text: "Accompagnement jusqu'à l'autonomie de vos équipes" }
];

const ListRow6_data = [
    { description: "8 semaines, 18 modules, 16 séances live, soutenance finale" },
    { description: "Tarif sur demande, facturation à l'organisation" },
    { description: "Un accompagnement continu, de la première séance à la mise en œuvre" }
];
const FeatureCard_data = [
    { title: "Former vos équipes", description: "Des séances ancrées dans vos processus réels, dès le premier jour." },
    { title: "Identifier les cas d'usage", description: "Un diagnostic pour prioriser là où l'IA crée de la valeur mesurable." },
    { title: "Construire des workflows", description: "Automatisation, agents IA et nouveaux modes de travail, adaptés à vos contraintes." }
];
const ListRow6_data2 = [
    { description: "Former vos équipes et identifier les cas d'usage" },
    { description: "Construire des workflows et automatiser" },
    { description: "Accompagner la transformation des organisations" }
];
const ListRow_data2 = [
    { href: "/formations/expert-ia", label: "Expert IA" },
    { href: "/formations/automatisation-n8n", label: "Automatisation & n8n" },
    { href: "/formations/robotique", label: "Robotique" },
    { href: "/formations/ia-recherche-sciences", label: "IA, Recherche & Sciences" }
];
const ListRow7_data = [
    { href: "/entreprises", ariacurrent: "page", label: "Entreprises" }
];
const ListRow8_data = [
    { href: "https://wa.me/243792369704", label: "WHATSAPP" },
    { href: "mailto:info@hoja-academy.com", label: "LINKEDIN" },
    { href: "https://hojanetwork.org", label: "HOJA NETWORK" },
    { href: "https://hojanetwork.org", label: "HOJA NETWORK" }
];
const ListRow9_data = [
    { href: "/confidentialite", label: "Politique de Confidentialité & Conditions" },
    { href: "/cookies", label: "Politique des Cookies" },
    { href: "/mentions-legales", label: "Mentions Légales" },
    { href: "/accessibilite", label: "Accessibilité" },
    { href: "/entreprises", label: "Entreprises" }
];
const ListRow10_data = [
    { href: "/confidentialite", label: "Politique de Confidentialité & Conditions" },
    { href: "/cookies", label: "Politique des Cookies" },
    { href: "/mentions-legales", label: "Mentions Légales" },
    { href: "/accessibilite", label: "Accessibilité" },
    { href: "/entreprises", label: "Entreprises" }
];
const ListRow_meta: string[][] = [
    ["interaction-sm-1767225603097025-2", "n22"],
    ["n23", "n24"],
    ["n25", "style-wp-submit"],
    ["n27", "n28"]
];
const ListRow2_meta: string[][] = [
    ["n29", "style-div"],
    ["style-div-18", "style-div-2"],
    ["style-div-19", "style-div-3"]
];
const ListRow3_meta: string[][] = [
    ["n56", "n57"],
    ["n58", "n59"],
    ["n60", "n61"]
];
const ListRow4_meta: string[][] = [
    ["n79", "n80"],
    ["n81", "n82"],
    ["n83", "n84"]
];
const ListRow5_meta: string[][] = [
    ["style-b-2"],
    ["interaction-li"],
    ["style-b-6"]
];
const ListRow5_meta2: string[][] = [
    ["style-div-97"],
    ["n244"],
    ["style-div-27"]
];
const ListRow6_meta: string[][] = [
    ["n344", "n345"],
    ["n346", "style-div-60"],
    ["style-div-68", "style-div-61"]
];
const FeatureCard_meta: string[][] = [
    ["n379", "n380", "n381", "n382", "n383", "n384", "style-div-55", "style-div-93", "style-a-5"],
    ["n388", "style-span-44", "interaction-div-20", "n391", "n392", "n393", "n394", "n395", "n396"],
    ["n397", "n398", "style-sin-completar-2", "n400", "n401", "style-div-74", "n403", "n404", "n405"]
];
const ListRow6_meta2: string[][] = [
    ["interaction-div-15", "n426"],
    ["style-link-10", "style-not-started"],
    ["n429", "n430"]
];
const ListRow_meta2: string[][] = [
    ["n489", "n490"],
    ["interaction-ld-expand-17973-container", "n492"],
    ["style-div-87", "interaction-div-19"],
    ["n495", "n496"]
];
const ListRow7_meta: string[][] = [
    ["style-span-15", "n498"],
    ["n499", "n500"],
    ["n501", "n502"]
];
const ListRow8_meta: string[][] = [
    ["n515", "n516", "n517"],
    ["n518", "n519", "n520"],
    ["n521", "n522", "n523"],
    ["n524", "n525", "style-not-completed"]
];
const ListRow9_meta: string[][] = [
    ["style-not-started-4", "style-div-32"],
    ["n553", "style-span-34"],
    ["n555", "n556"],
    ["n557", "n558"],
    ["style-div-26", "n560"]
];
const ListRow10_meta: string[][] = [
    ["interaction-div-11", "n566"],
    ["n567", "n568"],
    ["n569", "n570"],
    ["n571", "n572"],
    ["n573", "n574"]
];
const ListRow_styles = [
    { className: "rounded-tl-[25px] rounded-tr-[25px]" },
    {  },
    {  },
    { className: "rounded-br-[25px] rounded-bl-[25px]" }
,
    { className: "" }];
const ListRow2_styles = [
    { className: "mx-[0.5px] text-color-001 2xl:mx-[9.5px] before:opacity-0 after:right-[6.5625rem] after:opacity-0 2xl:after:right-29.5" },
    { className: "mx-[0.5px] text-primary-text 2xl:mx-[9.5px] before: before:origin-[56.5px_25px] max-lg:before:transform-[none] max-lg:before:origin-[initial] 2xl:before:origin-[65.5px_25px] after:right-[6.0625rem] after: after:origin-[0px_0px] max-lg:after:transform-[none] max-lg:after:origin-[initial] 2xl:after:right-[6.9375rem]" },
    { className: "ml-[0.5px] text-color-001 2xl:ml-[9.5px] before:opacity-0 after:right-[5.0625rem] after:opacity-0 2xl:after:right-[5.8125rem]" }
,
    { className: "" },
    { className: "" }];
const ListRow3_styles = [
    { className: "text-color-001" },
    { className: "text-primary-text bg-color-001" },
    { className: "text-color-001 max-lg:rounded-br-[10px] max-lg:rounded-bl-[10px]" }
,
    { className: "" },
    { className: "" }];
const ListRow4_styles = [
    { className: "mx-[0.5px] text-color-001 2xl:mx-[9.5px] before:opacity-0 after:right-[6.5625rem] after:opacity-0 2xl:after:right-29.5" },
    { className: "mx-[0.5px] text-primary-text 2xl:mx-[9.5px] before: before:origin-[56.5px_25px] max-lg:before:transform-[none] max-lg:before:origin-[initial] 2xl:before:origin-[65.5px_25px] after:right-[6.0625rem] after: after:origin-[0px_0px] max-lg:after:transform-[none] max-lg:after:origin-[initial] 2xl:after:right-[6.9375rem]" },
    { className: "ml-[0.5px] text-color-001 2xl:ml-[9.5px] before:opacity-0 after:right-[5.0625rem] after:opacity-0 2xl:after:right-[5.8125rem]" }
,
    { className: "" },
    { className: "" }];
const FeatureCard_styles = [
    { className: "max-md:mb-2.5", className2: "h-[7.275rem] m-px md:max-lg:h-[13.5875rem]", className3: "md:max-lg:h-[16.9375rem]" },
    { className: "max-md:mb-2.5", className2: "h-[7.2125rem] md:max-lg:h-[13.525rem]", className3: "md:max-lg:h-[16.9375rem]" },
    { className2: "h-[7.2125rem] max-md:m-2.5 md:max-lg:h-[13.525rem]", className3: "md:max-lg:h-[21.0625rem]" }
,
    { className: "" },
    { className: "" }];
const ListRow_styles2 = [
    { className: "rounded-tl-[15px] rounded-tr-[15px]" },
    {  },
    {  },
    { className: "rounded-br-[15px] rounded-bl-[15px]" }
,
    { className: "" }];
const ListRow7_styles = [
    { className: "mx-[17.5px] text-background max-md:mx-[0.5625rem] 2xl:mx-[21.5px]" },
    { className: "mx-[17.5px] text-primary-text max-md:mx-[0.5625rem] 2xl:mx-[21.5px]" },
    { className: "ml-[17.5px] text-background max-md:ml-[0.5625rem] 2xl:ml-[21.5px]" }
,
    { className: "" },
    { className: "" }];
const ListRow9_styles = [
    { className: "mr-[8.5px] 2xl:mr-[9.5px]" },
    { className: "mx-[8.5px] 2xl:mx-[9.5px]" },
    { className: "mx-[8.5px] 2xl:mx-[9.5px]" },
    { className: "mx-[8.5px] 2xl:mx-[9.5px]" },
    { className: "ml-[8.5px] 2xl:ml-[9.5px]" }
];
const ListRow10_styles = [
    { className: "mr-[8.5px] max-md:mr-[0.4375rem]" },
    { className: "mx-[8.5px] max-md:mx-[0.4375rem]" },
    { className: "mx-[8.5px] max-md:mx-[0.4375rem]" },
    { className: "mx-[8.5px] max-md:mx-[0.4375rem]" },
    { className: "ml-[8.5px] max-md:ml-[0.4375rem]" }
];

export const metadata = {
  title: 'Formations IA pour entreprises | HOJA ACADEMY',
  description: 'Formations et accompagnement en IA pour les organisations : diagnostic, cas d\'usage, workflows, automatisation, transformation des équipes.',
};
export default function Page() {
  return (
    <>
      {" "}
      <a className="w-px h-px block absolute -top-37500 left-0 -m-px overflow-hidden text-color-001 [font-family:Montserrat,_sans-serif] text-[0.9375rem] font-medium leading-[1.1875rem] [clip-path:inset(50%)] cursor-pointer" href="#content">
        Aller au contenu
      </a>
      {" "}
      <Navbar />
      {" "}
      <main className="block" id="content">
        {" "}
        <div className="block">
          <div className="block">
            <div className="min-h-140 flex relative max-w-full -mt-28 flex-col justify-between items-center bg-cover [background-position:50%_50%] bg-no-repeat max-md:pt-5 max-md:pb-7.5 max-md:px-5 max-md:flex-wrap max-md:justify-center max-lg:gap-y-[1.5625rem] max-md:min-h-0 md:max-lg:min-h-192 2xl:min-h-189" style={{ backgroundImage: "url(\"/assets/cloned/images/87b3a88d3b83.webp\")" }}>
              <div className="w-full min-h-140 flex relative [mix-blend-mode:difference] min-w-0 flex-col [background-position:-216px_-13px] bg-no-repeat max-md:flex-wrap max-md:[background-size:411px] max-md:[background-position:50%_100%] max-md:min-h-0 md:max-lg:min-h-[798.7px] md:max-lg:[background-size:70%] 2xl:min-h-189" style={{ backgroundImage: "url(\"/assets/cloned/images/27b42311f2ad.png\")" }} id="background">
                <div className="w-full min-h-126.5 flex relative min-w-0 pb-16 flex-col justify-end max-md:pb-[1.05rem] max-md:flex-wrap max-md:min-h-0 md:max-lg:min-h-140.5 md:max-lg:pb-[2.4rem] 2xl:min-h-150.5 2xl:pb-24">
                  <div className="w-full flex relative min-w-0 flex-col justify-center items-center max-md:flex-wrap max-lg:gap-y-[1.3125rem]">
                    <div className="w-full block relative min-w-0 max-w-full shrink-0 max-lg:gap-y-[1.3125rem]" data-ditto-id="style-span-39">
                      <div className="block" data-ditto-id="style-section">
                        <div className="block" data-ditto-id="style-div-83">
                          <div className="h-[4.3125rem] block max-md:h-37.5" data-ditto-id="style-p-10" />
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <div className="w-full flex relative min-w-0 p-2.5 justify-center items-center self-center gap-5 max-md:flex-wrap max-md:p-0" data-ditto-id="style-heading-4">
                      <div className="block relative min-w-0 max-w-full self-center gap-5" data-ditto-id="style-div-84">
                        <div className="block mt-[0.5625rem]" data-ditto-id="style-span-40">
                          <div className="block max-md:text-center 2xl:text-end">
                            <div className="inline-block text-color-001 text-[3.0625rem] leading-[3.0625rem] text-center max-md:text-[1.625rem] max-md:leading-6.5 max-md:[text-align:inherit]" data-ditto-id="interaction-span-11">
                              {" "}
                              <svg className="w-[3.0625rem] h-[3.0625rem] block relative overflow-hidden max-md:w-6.5 max-md:h-6.5" data-component="image" height="31" viewBox="0 0 69 31" width="69" xmlns="http://www.w3.org/2000/svg" fill="currentColor">
                                <g id="Grupo_241" data-name="Grupo 241" transform="translate(-251 -1259)">
                                  <path id="Vector_168" data-name="Vector 168" d="M20.165,0l3.112,3.13L20.165,6.26m3.112-3.13H0" transform="translate(283 1271.37)" fill="none" stroke="#fff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1" style={{ isolation: "isolate" }} />
                                  <g id="Rectángulo_144" data-name="Rectángulo 144" transform="translate(251 1259)" fill="none" stroke="#fff" strokeWidth="1">
                                    <rect width="69" height="31" rx="15.5" stroke="none" />
                                    <rect x="0.5" y="0.5" width="68" height="30" rx="15" fill="none" />
                                  </g>
                                </g>
                              </svg>
                              {" "}
                            </div>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                      <div className="w-[19.6875rem] block relative min-w-0 max-w-full shrink-0 gap-5 max-md:w-[204.3px] max-md:self-center md:max-lg:w-[7.95rem] 2xl:w-85" data-ditto-id="style-section-2">
                        <div className="block" data-ditto-id="interaction-div-26">
                          <h3 className="block text-primary-text text-[1.1875rem] leading-5.5 uppercase max-md:text-[0.75rem] 2xl:text-[1.4375rem]" data-component="heading">
                            ENTREPRISES & INSTITUTIONS
                          </h3>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <div className="w-full flex relative min-w-0 p-2.5 flex-col gap-5 max-md:-mt-[1.1875rem] max-md:flex-wrap">
                      <div className="w-134.5 block relative min-w-0 max-w-full self-center shrink-0 gap-5 text-center max-md:w-[19.6875rem] 2xl:w-475" data-ditto-id="style-p-6">
                        <div className="block">
                          <h2 className="block text-background [font-family:Montserrat,_sans-serif] text-[3.125rem] leading-16.5 max-md:text-3xl max-md:leading-[inherit] 2xl:text-[5.3125rem] 2xl:leading-[6.3125rem]" data-ditto-id="style-p-13" data-component="heading">
                            L'IA ne doit pas rester une expérimentation.
                          </h2>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                      <div className="block relative min-w-0 max-w-full self-center gap-5 text-center" data-ditto-id="style-p-7">
                        <div className="block pt-[2.0625rem] max-lg:pt-0 2xl:pt-13">
                          <div className="block text-background text-[1.1875rem] font-light leading-6 max-md:text-base max-md:leading-[1.375rem] 2xl:text-[1.625rem]" data-ditto-id="style-div-101" data-component="heading">
                            <p className="block">
                              <b className="inline text-primary-text font-normal">
                                Hoja Academy accompagne les organisations qui passent de la curiosité
                              </b>
                              <br className="inline" />
                              {" à des usages concrets et mesurables. "}
                            </p>
                          </div>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
                <div className="flex relative min-w-0 -mt-[2.8125rem] p-2.5 flex-col justify-center gap-5 max-md:gap-3 max-md:flex-wrap">
                  <div className="block relative min-w-0 max-w-full self-center gap-5" data-ditto-id="style-p-14">
                    <div className="block py-4 px-8">
                      <div className="block" data-ditto-id="style-p-11">
                        <a className="h-[2.6875rem] inline-block py-3 px-6 rounded-[25px] text-color-007 [font-family:Montserrat,_sans-serif] text-base font-semibold leading-[1.1875rem] text-center bg-primary shadow-[var(--clr-19)_0px_0px_10px_0px] cursor-pointer max-md:text-[0.9375rem]" data-ditto-id="style-p-8" data-component="link" href="/contact" target="_blank">
                          {" "}
                          <span className="flex justify-center gap-[0.3125rem]" data-ditto-id="style-p-9">
                            {" "}
                            <span className="block whitespace-nowrap" data-ditto-id="interaction-p">
                              Demander un premier échange
                            </span>
                            {" "}
                          </span>
                          {" "}
                        </a>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                  <div className="block relative min-w-0 max-w-full self-center gap-5" data-ditto-id="style-p-12">
                    <div className="block py-4 px-8" data-ditto-id="style-p-4">
                      <div className="block" data-ditto-id="interaction-p-2">
                        <a className="h-[2.9375rem] border-2 border-solid border-primary inline-block py-3 px-6 text-background [font-family:Montserrat,_sans-serif] text-base font-semibold leading-[1.1875rem] text-center bg-clr-3 shadow-[var(--clr-19)_0px_0px_10px_0px] cursor-pointer max-md:text-[0.9375rem]" data-ditto-id="interaction-p-3" data-component="link" href="#formaciones">
                          {" "}
                          <span className="flex justify-center gap-[0.3125rem]" data-ditto-id="interaction-button">
                            {" "}
                            <span className="block whitespace-nowrap" data-ditto-id="interaction-span-3">
                              Voir les formations
                            </span>
                            {" "}
                          </span>
                          {" "}
                        </a>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
                <div className="w-full h-[3.3125rem] block relative min-w-0 max-w-full [animation-name:bounce] [animation-duration:1.25s] max-md:w-[13%] max-md:self-center 2xl:h-14" data-ditto-id="style-p">
                  <div className="block" data-ditto-id="interaction-link">
                    <div className="block text-center" data-ditto-id="interaction-span-4">
                      <div className="inline-block text-color-001 text-[2.75rem] leading-11 2xl:text-[2.9375rem] 2xl:leading-[2.9375rem]" data-ditto-id="style-navegaci-n-entre-noticias-del-d-a">
                        {" "}
                        <svg className="w-auto h-11 block relative overflow-hidden 2xl:h-[2.9375rem]" data-ditto-id="style-link-7" data-component="icon" height="37" viewBox="0 0 37 37" width="37" xmlns="http://www.w3.org/2000/svg" fill="currentColor">
                          <g id="icon_scroll" data-name="icon scroll" transform="translate(37) rotate(90)" style={{ mixBlendMode: "normal", isolation: "isolate" }}>
                            <g id="Ellipse_136" data-name="Ellipse 136" fill="none" style={{ mixBlendMode: "normal", isolation: "isolate" }}>
                              <path d="M0,18.5A18.5,18.5,0,1,1,18.5,37,18.5,18.5,0,0,1,0,18.5Z" stroke="none" />
                              <path d="M 18.5 1 C 13.82558059692383 1 9.430940628051758 2.820320129394531 6.125629425048828 6.125629425048828 C 2.820320129394531 9.430940628051758 1 13.82558059692383 1 18.5 C 1 23.17443084716797 2.820320129394531 27.56906890869141 6.125629425048828 30.87438011169434 C 9.430940628051758 34.17969131469727 13.82558059692383 36 18.5 36 C 23.17443084716797 36 27.56906890869141 34.17969131469727 30.87438011169434 30.87438011169434 C 34.17969131469727 27.56906890869141 36 23.17443084716797 36 18.5 C 36 13.82558059692383 34.17969131469727 9.430940628051758 30.87438011169434 6.125629425048828 C 27.56906890869141 2.820320129394531 23.17443084716797 1 18.5 1 M 18.5 0 C 28.71730041503906 0 37 8.282730102539062 37 18.5 C 37 28.71730041503906 28.71730041503906 37 18.5 37 C 8.282730102539062 37 0 28.71730041503906 0 18.5 C 0 8.282730102539062 8.282730102539062 0 18.5 0 Z" stroke="none" fill="#fff" />
                            </g>
                            <path id="Vector_168" data-name="Vector 168" d="M3.5,0,7,3.5,3.5,7M7,3.5H0" transform="translate(15 15)" fill="none" stroke="#fff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1" style={{ mixBlendMode: "normal", isolation: "isolate" }} />
                          </g>
                        </svg>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
                <div className="block relative min-w-0 max-w-full" data-ditto-id="style-br-3">
                  <div className="block">
                    <div className="block" id="formaciones" />
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
                <div className="block relative min-w-0 max-w-full shrink-0">
                  <div className="block">
                    <div className="block" data-ditto-id="style-br-2">
                      <div className="h-12.5 block" data-ditto-id="interaction-br" />
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
            <div className="w-full py-16 md:py-20 flex relative max-w-full flex-col items-center shrink-0 bg-clr-27 [background-position:100%_0%] bg-no-repeat max-md:py-10 max-md:px-5 max-md:flex-wrap max-md:justify-center md:max-lg:pb-12.5" style={{ backgroundImage: "url(\"/assets/cloned/svg/88d6f0c03d30.svg\")" }}>
              <div className="w-full flex relative min-w-0 px-2.5 flex-col max-md:px-5 max-md:self-center" data-ditto-id="style-br">
                <div className="flex max-w-[min(100%,_1140px)] mx-15 py-2.5 flex-col grow gap-5 max-md:max-w-[min(100%,_767px)] max-md:py-10 max-md:flex-wrap max-md:justify-center max-md:items-center max-lg:mx-0 md:max-lg:max-w-[min(100%,_1024px)] 2xl:mx-95" data-ditto-id="interaction-span">
                  <div className="w-285 block relative min-w-0 max-w-full shrink-0 gap-5 max-md:w-[18.4375rem] md:max-lg:w-187">
                    <div className="block">
                      <div className="block" data-ditto-id="style-span-47">
                        <div className="h-12.5 block max-md:h-0" />
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                  <div className="w-285 block relative min-w-0 max-w-full self-center shrink-0 gap-5 text-center max-md:w-[18.4375rem] md:max-lg:w-187">
                    <div className="block mt-7.5" data-ditto-id="style-p-15">
                      <div className="block text-color-016 [font-family:Montserrat,_sans-serif] text-[2.8125rem] leading-16.5 max-md:text-3xl max-md:leading-9" data-ditto-id="style-footer-3" data-component="heading">
                        <p className="block mb-[0.9rem]">
                          <b className="inline font-bold" data-ditto-id="interaction-div-7">
                            Ce que nous pouvons faire avec votre organisation
                          </b>
                        </p>
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                  <div className="block relative min-w-0 max-w-full gap-5 text-color-016 text-[1.375rem] text-center max-md:text-[0.875rem]">
                    <div className="block my-5" data-ditto-id="interaction-div-6">
                      <p className="block mb-[0.9rem]" data-ditto-id="interaction-div-8">
                        <b className="inline font-bold" data-ditto-id="style-menu-2">
                          {" Une démarche complète : "}
                        </b>
                        diagnostic, formation, expérimentation, mise en œuvre, accompagnement
                      </p>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                  <div className="w-285 block relative min-w-0 max-w-full shrink-0 gap-5 max-md:w-[18.4375rem] md:max-lg:w-187" data-ditto-id="interaction-menu-1-516d334">
                    <div className="block">
                      <div className="block" data-ditto-id="style-link-32">
                        <div className="h-12.5 block" data-ditto-id="interaction-li-2" />
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                  <div className="block relative min-w-0 max-w-full gap-5 text-color-010 text-[1.5625rem] text-center max-md:self-center max-md:text-[1.125rem]" data-ditto-id="interaction-sm-17672256027865476-1">
                    <div className="block mt-3 mb-[2.1875rem] max-md:mt-0" data-ditto-id="style-span-6">
                      <h3 className="block mt-2 mb-4 text-[1.6875rem] font-medium leading-[2.6875rem]" data-ditto-id="style-icon-2" data-component="heading">
                        <span className="inline text-color-007" data-ditto-id="interaction-sm-17672256027865476-2">
                          <b className="inline font-bold">
                            Trois formats, selon votre point de départ :
                          </b>
                        </span>
                      </h3>
                      <p className="block mb-[0.9rem]">
                        en direct, à votre rythme ou sur mesure
                        <b className="inline font-bold" data-ditto-id="style-p-2" />
                      </p>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                  <div className="w-full max-w-5xl mx-auto flex flex-wrap justify-center items-stretch gap-6 px-4" data-ditto-id="style-b-5">
                    {/* Carte 1 : Formation en direct */}
                    <div className="w-full md:w-[26rem] border border-solid border-surface-4 flex flex-col justify-between p-8 rounded-2xl bg-color-040 shadow-[var(--clr-19)_0px_10px_30px_0px]">
                      <div className="flex flex-col gap-5">
                        <div className="flex items-center justify-center gap-3">
                          <img className="w-10 h-auto inline-block" alt="" height="23" src="/assets/cloned/svg/13f2fd4da1c4.svg" width="52" />
                          <span className="text-color-001 [font-family:Montserrat,_sans-serif] text-[0.875rem] font-bold tracking-wider uppercase">
                            FORMATION EN DIRECT
                          </span>
                        </div>

                        <div className="text-center">
                          <h4 className="text-color-016 text-[1.6875rem] font-black leading-tight mb-2">
                            Programme Intensif IA
                          </h4>
                          <p className="text-color-010 text-sm leading-relaxed">
                            8 semaines, 18 modules, 16 séances en direct et une soutenance finale : vos équipes maîtrisent l'IA générative sur leurs propres cas de travail.
                          </p>
                        </div>

                        <div className="text-color-010 text-sm">
                          <ul className="pl-6 list-disc space-y-2">
                            {ListRow5_data.map((d, i) => <ListRow5 key={i} d={d} />)}
                          </ul>
                        </div>
                      </div>

                      <div className="flex flex-col items-center gap-6 mt-8">
                        <img className="w-48 h-auto inline-block" alt="Formation IA pour equipes" height="534" src="/assets/hoja/badge-entreprises.png" width="800" />
                        <a className="w-full max-w-xs py-3 px-6 rounded-[25px] text-background [font-family:Montserrat,_sans-serif] text-sm font-semibold text-center bg-color-016 hover:opacity-90 transition-opacity" href="/formations">
                          Voir le programme
                        </a>
                      </div>
                    </div>

                    {/* Carte 2 : Formation sur mesure */}
                    <div className="w-full md:w-[26rem] border border-solid border-surface-4 flex flex-col justify-between p-8 rounded-2xl bg-color-040 shadow-[var(--clr-19)_0px_10px_30px_0px]">
                      <div className="flex flex-col gap-5">
                        <div className="flex items-center justify-center gap-3">
                          <img className="w-10 h-auto inline-block" alt="" height="23" src="/assets/cloned/svg/13f2fd4da1c4.svg" width="52" />
                          <span className="text-color-001 [font-family:Montserrat,_sans-serif] text-[0.875rem] font-bold tracking-wider uppercase">
                            FORMATION SUR MESURE
                          </span>
                        </div>

                        <div className="text-center">
                          <h4 className="text-color-016 text-[1.6875rem] font-black leading-tight mb-2">
                            Formation adaptée à votre équipe
                          </h4>
                          <p className="text-color-010 text-sm leading-relaxed">
                            Partir de vos usages réels : identifier les cas d'usage, construire des workflows, automatiser — puis mesurer l'impact avec vous.
                          </p>
                        </div>

                        <div className="text-color-010 text-sm">
                          <ul className="pl-6 list-disc space-y-2">
                            {ListRow5_data2.map((d, i) => <ListRow5 key={i} d={d} />)}
                          </ul>
                        </div>
                      </div>

                      <div className="flex flex-col items-center gap-6 mt-8">
                        <a className="w-full max-w-xs py-3 px-6 rounded-[25px] text-background [font-family:Montserrat,_sans-serif] text-sm font-semibold text-center bg-color-016 hover:opacity-90 transition-opacity" href="/contact">
                          Racontez-nous votre cas
                        </a>
                      </div>
                    </div>
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
              {" "}
              <div className="w-full block relative min-w-0 max-w-full shrink-0" data-ditto-id="interaction-gt-wrapper-30105788">
                <div className="block" data-ditto-id="style-english-2">
                  <div className="block" data-ditto-id="style-spanish-2">
                    <div className="h-19.5 block" />
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
              <div className="w-full min-h-44 border border-solid border-surface-4 flex relative z-2 min-w-0 rounded-[1px] flex-col justify-center items-center max-md:min-h-[12.6875rem] max-md:flex-wrap md:max-lg:min-h-[184.3px] 2xl:min-h-[14.85rem]" style={{ backgroundImage: "linear-gradient(120deg, var(--background) 0%, var(--clr-28) 100%)" }} data-ditto-id="interaction-div-9">
                <div className="w-full flex relative z-2 min-w-0 mb-12.5 px-2.5 flex-col shrink-0 max-md:w-[20.8125rem] md:max-lg:w-191.5 2xl:w-479.5" data-ditto-id="interaction-div-23">
                  <div className="flex max-w-239 mx-[9.4375rem] py-2.5 flex-col justify-start items-start grow gap-5 max-md:max-w-[min(100%,_767px)] max-md:flex-wrap max-lg:mx-0 2xl:mx-[29.4375rem]">
                    <div className="block relative min-w-0 max-w-full gap-5 max-md:self-center max-md:text-center" data-ditto-id="style-div-90">
                      <div className="block mt-[2.1875rem]" data-ditto-id="style-div-91">
                        <div className="block text-color-016 [font-family:Montserrat,_sans-serif] text-[2.8125rem] leading-16.5 max-md:text-[1.875rem]" data-component="heading">
                          <p className="block mb-[0.9rem]">
                            <b className="inline font-bold">
                              Des programmes conçus pour les organisations, sur site ou à distance
                            </b>
                            <span className="inline" />
                          </p>
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <div className="block relative min-w-0 max-w-full gap-5 text-color-010 text-[1.0625rem] leading-[1.5rem] max-md:text-base max-md:leading-[1.375rem]">
                      <div className="block">
                        <p className="block mb-[0.9rem]">
                          {"Un plan de formation sur mesure est établi selon vos objectifs, vos effectifs et vos contraintes opérationnelles. "}
                          <strong className="inline font-bold" data-ditto-id="style-div-92">
                          </strong>
                          <b className="inline font-bold" />
                        </p>
                        <p className="block mb-[0.9rem]">
                          <b className="inline font-bold" data-ditto-id="style-svg-2">
                            Le Programme Intensif d'IA Générative est facturé aux organisations —
                          </b>
                          <span className="inline">
                            {" tarif sur demande, "}
                          </span>
                          <b className="inline font-bold">
                            modalités définies avec vous.
                          </b>
                        </p>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <div className="w-full max-w-112 block relative min-w-0 gap-5 text-color-010 text-[1rem] max-md:text-[0.9375rem]">
                      <div className="block">
                        <ul className="block pl-10 [list-style-type:disc] list-outside">
                          {ListRow6_data.map((d, i) => <ListRow6 key={i} d={d} meta={ListRow6_meta[i]} />)}
                        </ul>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <div className="block relative min-w-0 max-w-full self-center gap-5 text-center" data-ditto-id="style-div-69">
                      <div className="block -ml-10">
                        <div className="block" data-ditto-id="style-div-70">
                          <a className="h-[3.8375rem] inline-block p-3.5 rounded-[25px] text-background [font-family:Montserrat,_sans-serif] text-[0.9375rem] font-medium leading-[1.1875rem] bg-color-016 cursor-pointer" data-ditto-id="style-div-71" data-component="link" href={"mailto:info@hoja-academy.com?subject=Demande%20-%20Formation%20IA%20pour%20organisation&body=(Indiquez-nous%20votre%20organisation%2C%20vos%20effectifs%20et%20vos%20objectifs%20%3B%20nous%20reviendrons%20vers%20vous%20rapidement%20et%20sans%20engagement.)"} target="_blank">
                            {" "}
                            <span className="flex justify-center gap-[0.3125rem]" data-ditto-id="style-link-9">
                              {" "}
                              <span className="block" data-ditto-id="style-not-started-5">
                                <p className="block mb-[0.9rem]" data-ditto-id="style-div-72">
                                  <b className="inline font-bold">
                                    Écrire à Hoja Academy
                                  </b>
                                </p>
                              </span>
                              {" "}
                            </span>
                            {" "}
                          </a>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
              <div className="w-full py-16 md:py-20 flex relative min-w-0 flex-col shrink-0 bg-color-001 [background-size:1250px] [background-position:100%_100%] bg-no-repeat max-md:pb-12.5 max-lg:px-10 max-md:flex-wrap 2xl:[background-size:75%]" style={{ backgroundImage: "url(\"/assets/cloned/svg/1b3f50d6645a.svg\")" }}>
                <div className="w-full flex relative min-w-0 flex-col">
                  <div className="flex max-w-[min(100%,_1140px)] mx-17.5 flex-col grow max-md:max-w-[min(100%,_767px)] max-md:flex-wrap max-lg:mx-0 md:max-lg:max-w-[min(100%,_1024px)] 2xl:mx-97.5">
                    <div className="w-full flex relative min-w-0 p-2.5 flex-col gap-5 max-md:flex-wrap">
                      <div className="w-143 block relative min-w-0 max-w-full self-start shrink-0 gap-5 max-md:w-[14.6875rem] 2xl:w-200">
                        <div className="block">
                          <img className="w-[6.0625rem] h-[6.0625rem] inline-block max-w-[17%] overflow-clip aspect-[auto_800/800] align-middle max-md:w-10 max-md:h-10 2xl:w-34 2xl:h-34" data-ditto-id="style-button-2" data-component="image" alt="Emblème HOJA ACADEMY" height="800" sizes="(max-width: 800px) 100vw, 800px" src="/assets/hoja/hoja-emblem.png" srcSet="/assets/hoja/hoja-emblem.png 512w" width="800" />
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                      <div className="w-full max-w-183 block relative min-w-0 self-center gap-5 text-color-001 text-center" data-ditto-id="style-span-14">
                        <div className="block" data-ditto-id="style-span-45">
                          <h4 className="block mt-2 mb-4 text-[1.4375rem] leading-8.5" data-ditto-id="style-span-31" data-component="heading">
                            <span className="inline text-background">
                              {"Les organisations ne cherchent pas des cours d'IA — "}
                            </span>
                          </h4>
                          <h4 className="block mt-2 mb-4 text-[1.4375rem] leading-8.5" data-ditto-id="interaction-ld-expand-17948-container" data-component="heading">
                            <span className="inline text-background" data-ditto-id="style-ld-expand-17948">
                              elles cherchent des usages concrets et mesurables.
                            </span>
                          </h4>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                      <div className="block relative min-w-0 max-w-full gap-5 text-center">
                        <div className="block">
                          <h2 className="block text-background [font-family:Montserrat,_sans-serif] text-[2.8125rem] leading-16.5 max-md:text-[1.4375rem]" data-component="heading">
                            Pourquoi choisir HOJA ACADEMY
                          </h2>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                      <div className="w-280 block relative min-w-0 max-w-full shrink-0 gap-5 max-md:w-[14.6875rem] md:max-lg:w-167" data-ditto-id="style-span-10">
                        <div className="block">
                          <div className="block">
                            <div className="h-12.5 block" />
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <div className="flex relative min-w-0 py-8 px-4 flex-wrap md:flex-nowrap gap-6 justify-center items-stretch max-w-5xl mx-auto" data-ditto-id="interaction-span-5">
                      {FeatureCard_data.map((d, i) => <FeatureCard key={i} d={d} styles={FeatureCard_styles[i]} />)}
                      {" "}
                    </div>
                    {" "}
                    <div className="block relative min-w-0 max-w-full text-color-001">
                      <div className="block">
                        <p className="block mb-[0.9rem] text-center">
                          <span className="inline text-background">
                            Une démarche présentée comme un cheminement, pas un contrat rigide : vos équipes intègrent l'IA dans leur quotidien et obtiennent des améliorations mesurables.
                          </span>
                        </p>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
                <div className="w-full flex relative min-w-0 px-10 flex-col">
                  <div className="flex max-w-275 mx-12.5 py-20 justify-between items-center grow gap-5 max-md:max-w-[min(100%,_767px)] max-md:flex-wrap max-lg:mx-0 2xl:mx-92.5">
                    <div className="w-full flex relative min-w-0 pr-7.5 flex-col justify-center items-start gap-5 max-md:flex-wrap" data-ditto-id="style-link-27">
                      <div className="w-full max-w-[9.3125rem] block relative min-w-0 gap-5 text-primary-text [font-family:Montserrat,_sans-serif] text-[0.9375rem] font-medium leading-[1.1875rem]">
                        <div className="block">
                          <p className="block mb-[0.9rem]">
                            NOTRE DÉMARCHE
                          </p>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                      <div className="w-127.5 block relative min-w-0 max-w-full shrink-0 gap-5 max-md:w-[9.0625rem] md:max-lg:w-66">
                        <div className="block" data-ditto-id="style-ld-table-list-item-22013">
                          <h2 className="block text-background [font-family:Montserrat,_sans-serif] text-4xl font-semibold leading-[2.6875rem] max-md:text-[1.4375rem] max-md:leading-[1.75rem]" data-ditto-id="style-ld-table-list-item-20883" data-component="heading">
                            Diagnostic → Formation → Expérimentation → Mise en œuvre → Accompagnement
                          </h2>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                      <div className="w-127.5 block relative min-w-0 max-w-full shrink-0 gap-5 text-color-012 text-[1.0625rem] leading-[1.5rem] max-md:w-[9.0625rem] max-md:text-[0.9375rem] max-md:leading-[1.4375rem] md:max-lg:w-66">
                        <div className="block max-md:px-5">
                          <p className="block mb-[0.9rem]" data-ditto-id="style-span-20">
                            Chaque étape s'adapte à votre contexte, portée par des praticiens de l'IA appliquée en organisation. Les secteurs accompagnés : entreprises privées, institutions publiques, cabinets professionnels, recherche et santé.
                          </p>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                      <div className="w-full max-w-101 block relative min-w-0 gap-5 text-color-012 text-[1rem]">
                        <div className="block">
                          <ul className="block pl-10 [list-style-type:disc] list-outside">
                            {ListRow6_data2.map((d, i) => <ListRow6 key={i} d={d} meta={ListRow6_meta2[i]} />)}
                          </ul>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                      <div className="w-127.5 block relative min-w-0 max-w-full shrink-0 gap-5 text-color-012 text-[1.0625rem] leading-[1.5rem] max-md:w-[9.0625rem] max-md:text-[0.9375rem] max-md:leading-[1.4375rem] md:max-lg:w-66" data-ditto-id="style-span-27">
                        <div className="block my-[1.5625rem] max-md:px-5" data-ditto-id="style-span-41">
                          <p className="block mb-[0.9rem]">
                            {" L'IA ne remplace pas vos experts : elle décharge leurs tâches répétitives pour qu'ils se concentrent sur la valeur. En santé comme dans le reste, la décision humaine reste entière."}
                          </p>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <div className="w-full flex relative min-w-0 pl-7.5 flex-col justify-center items-center gap-5 max-md:flex-wrap">
                      <div className="block relative min-w-0 max-w-full gap-5 text-center" data-ditto-id="style-div-88">
                        <div className="block" data-ditto-id="style-button-3">
                          <img className="w-73.5 h-73.5 inline-block max-w-full rounded-xl overflow-clip aspect-[auto_242/242] align-middle max-md:w-[7.0625rem] max-md:h-[7.0625rem] md:max-lg:w-66" data-ditto-id="style-span-11" data-component="image" alt="Membre de l’équipe pédagogique HOJA ACADEMY" height="242" sizes="(max-width: 242px) 100vw, 242px" src="/assets/hoja/hoja-team-tile.jpg" srcSet="/assets/hoja/hoja-team-tile.jpg 242w" width="242" />
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
              <div className="w-full flex relative min-w-0 py-20 px-10 flex-col items-center gap-5 bg-color-002 max-md:-mb-10 max-md:flex-wrap">
                <div className="w-full max-w-[68.9375rem] block relative min-w-0 gap-5 text-center">
                  <div className="block" data-ditto-id="interaction-ld-expand-17962-container">
                    <div className="block text-color-007 [font-family:Montserrat,_sans-serif] text-[2.8125rem] leading-16.5 max-md:text-[1.4375rem]" data-ditto-id="interaction-ld-expand-17962" data-component="heading">
                      <p className="block mb-[0.9rem]">
                        <b className="inline font-bold">
                          Quelle formation correspond le mieux à votre équipe ?
                        </b>
                        <br className="inline" />
                        <b className="inline font-bold">
                          Nous en discutons lors d'un premier échange
                        </b>
                      </p>
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
                <div className="w-full max-w-[47.6875rem] block relative min-w-0 gap-5 text-color-037 text-center max-md:text-[0.9375rem]">
                  <div className="block">
                    <p className="block mb-[0.9rem]">
                      <span className="inline text-color-007">
                        {" Nous analysons votre organisation, ses usages et ses contraintes, puis vous orientons vers la voie la plus adaptée."}
                      </span>
                    </p>
                    <p className="block mb-[0.9rem]">
                      <span className="inline text-color-007">
                        <b className="inline font-bold">
                          Et si vous cherchez quelque chose de plus spécifique
                        </b>
                        {" nous étudions ensemble une formation sur mesure."}
                      </span>
                      <b className="inline font-bold" data-ditto-id="style-div-59" />
                    </p>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
                <div className="block relative min-w-0 max-w-full gap-5">
                  <div className="block">
                    <div className="block">
                      <a className="h-[3.1875rem] inline-block py-4 px-10 rounded-[30px] text-color-052 [font-family:Montserrat,_sans-serif] text-lg font-medium leading-[1.1875rem] text-center [text-shadow:var(--clr-7)_0px_0px_10px] bg-primary cursor-pointer max-md:text-[0.9375rem]" data-ditto-id="style-span-37" data-component="link" href="/contact" target="_blank">
                        {" "}
                        <span className="flex justify-center gap-[0.3125rem]" data-ditto-id="style-div-81">
                          {" "}
                          <span className="block whitespace-nowrap">
                            Parler de votre organisation
                          </span>
                          {" "}
                        </span>
                        {" "}
                      </a>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
                <div className="w-full max-w-94.5 block relative min-w-0 gap-5 text-color-045 [font-family:Montserrat,_sans-serif] text-[0.9375rem] font-medium leading-[1.1875rem] text-center max-md:text-[0.875rem]">
                  <div className="block">
                    <p className="block mb-[0.9rem]">
                      <b className="inline font-bold" data-ditto-id="style-link-28">
                        Sans engagement · Entreprises, institutions, cabinets, recherche & santé
                      </b>
                    </p>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
              <div className="w-full block relative min-w-0 max-w-full shrink-0">
                <div className="block">
                  <div className="block" data-ditto-id="style-span-32">
                    <div className="h-12.5 block" />
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
            <div className="flex relative max-w-full px-2.5 flex-col">
              <div className="w-full flex max-w-[min(100%,_1140px)] mx-15 py-2.5 flex-col grow gap-5 max-md:max-w-[min(100%,_767px)] max-md:flex-wrap max-lg:mx-0 md:max-lg:max-w-[min(100%,_1024px)] 2xl:mx-95" data-ditto-id="style-div-75">
                <div className="w-full max-w-89.5 block relative min-w-0 self-center gap-5">
                  <div className="block">
                    <div className="block relative" data-ditto-id="style-span-21">
                      <p className="block mb-[0.9rem]">
                        Des professionnels de terrain vous accompagnent à chaque étape.
                      </p>
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </main>
      {" "}
      <Footer />
      {" "}
      <span className="w-1 h-1 border-2 border-inset border-foreground block absolute -top-[624.9375rem] overflow-clip" aria-hidden="true" role="presentation" title="Vidéo de présentation — HOJA ACADEMY"></span>
      {" "}
      <svg className="hidden overflow-hidden" fill="currentColor" />
      {" "} <div className="box-content w-15 h-15 block fixed right-5 bottom-5 z-9999 max-w-[calc(100%_-_40px)] max-h-[calc(100%_-_40px)]" id="brevo-conversations">
        <div className="w-15 h-full min-h-full block absolute top-0 min-w-full max-w-full max-h-full rounded-[50%] overflow-hidden shadow-[var(--clr-6)_0px_0px_3px_0px,var(--clr-7)_0px_0px_10px_0px]">
          <div className="w-15 h-15 min-h-full block absolute min-w-full max-w-full max-h-full overflow-hidden" title="Brevo live chat">
            <div className="box-content h-full block overflow-hidden text-color-006 [font-family:'Noto_Color_Emoji',_-apple-system,_BlinkMacSystemFont,_'Segoe_UI',_Roboto,_Oxygen,_Ubuntu,_Cantarell,_'Open_Sans',_'Helvetica_Neue',_sans-serif] text-base leading-6 [overflow-wrap:break-word]">
              <svg className="box-content hidden overflow-hidden" fill="currentColor">
                <defs>
                  <symbol id="ei-arrow-down-icon" viewBox="8 8 34 34">
                    <path d="M25 42c-9.4 0-17-7.6-17-17S15.6 8 25 8s17 7.6 17 17-7.6 17-17 17zm0-32c-8.3 0-15 6.7-15 15s6.7 15 15 15 15-6.7 15-15-6.7-15-15-15z" />
                    <path d="M25 34.4l-9.7-9.7 1.4-1.4 8.3 8.3 8.3-8.3 1.4 1.4z" />
                    <path d="M24 16h2v17h-2z" />
                  </symbol>
                  <symbol id="ei-arrow-up-icon" viewBox="0 0 50 50">
                    <path d="M25 42c-9.4 0-17-7.6-17-17S15.6 8 25 8s17 7.6 17 17-7.6 17-17 17zm0-32c-8.3 0-15 6.7-15 15s6.7 15 15 15 15-6.7 15-15-6.7-15-15-15z" />
                    <path d="M33.3 26.7L25 18.4l-8.3 8.3-1.4-1.4 9.7-9.7 9.7 9.7z" />
                    <path d="M24 17h2v17h-2z" />
                  </symbol>
                  <symbol id="ei-close-icon" viewBox="0 0 50 50">
                    <path d="M37.304 11.282l1.414 1.414-26.022 26.02-1.414-1.413z" />
                    <path d="M12.696 11.282l26.022 26.02-1.414 1.415-26.022-26.02z" />
                  </symbol>
                  <symbol id="ei-check-icon" viewBox="10 10 30 30">
                    <path d="M23 32.4l-8.7-8.7 1.4-1.4 7.3 7.3 11.3-11.3 1.4 1.4z" />
                  </symbol>
                  <symbol id="ei-exclamation-icon" viewBox="10 10 30 30">
                    <path d="M24 32h2v2h-2z" />
                    <path d="M25.6 30h-1.2l-.4-8v-6h2v6z" />
                  </symbol>
                  <symbol id="chat-icon-bubble" viewBox="0 0 512 512">
                    <path d="M240,0 C372.5625,0 480,87.1407005 480,194.68599 C480,302.23128 372.5625,389.371981 240,389.371981 C204,389.371981 169.96875,382.726449 139.3125,371.213768 C87.109375,400.003959 42.421875,400.003959 14.0814012,400.003959 C11.0814012,400.003959 42.421875,361.363406 53.4375,317.019928 C20.0625,283.605072 -2.84217094e-14,241.111111 -2.84217094e-14,194.68599 C-2.84217094e-14,87.1407005 107.4375,0 240,0 Z M240,24 C119.710468,24 24,101.636307 24,194.68599 C24,232.868518 40.0525875,269.249177 69.5210975,299.155237 L70.4181865,300.059495 L79.9976491,309.650397 L76.7295758,322.806049 C72.6472992,339.239283 66.0642369,355.61453 57.4845168,372.224794 L56.8030315,373.536625 L56.644,373.838 L56.8007345,373.81731 C58.8315421,373.534605 60.8948043,373.217509 63.0261395,372.862271 L63.7391546,372.74244 C84.9526326,369.14813 105.630175,362.220208 126.579252,350.82399 L127.722203,350.19794 L137.401761,344.859633 L147.75012,348.745867 C176.71924,359.624962 207.933528,365.371981 240,365.371981 C360.289532,365.371981 456,287.735673 456,194.68599 C456,101.636307 360.289532,24 240,24 Z" transform="translate(16 54)" />
                  </symbol>
                  <symbol id="chat-icon-bubbles" viewBox="0 0 576 512">
                    <path opacity="0.9" d="M208 352c-41 0-79.1-9.3-111.3-25-21.8 12.7-52.1 25-88.7 25a7.83 7.83 0 0 1-7.3-4.8 8 8 0 0 1 1.5-8.7c.3-.3 22.4-24.3 35.8-54.5-23.9-26.1-38-57.7-38-92C0 103.6 93.1 32 208 32s208 71.6 208 160-93.1 160-208 160z" />
                    <path opacity="0.4" d="M576 320c0 34.3-14.1 66-38 92 13.4 30.3 35.5 54.2 35.8 54.5a8 8 0 0 1 1.5 8.7 7.88 7.88 0 0 1-7.3 4.8c-36.6 0-66.9-12.3-88.7-25-32.2 15.8-70.3 25-111.3 25-86.2 0-160.2-40.4-191.7-97.9A299.82 299.82 0 0 0 208 384c132.3 0 240-86.1 240-192a148.61 148.61 0 0 0-1.3-20.1C522.5 195.8 576 253.1 576 320z" />
                  </symbol>
                  <symbol id="chat-icon-brevo" fill="none" viewBox="0 0 40 40">
                    <circle fill="currentColor" cx="20" cy="20" r="20" />
                    <path fill="#fff" d="M26.253 18.1743C27.4896 16.9636 28.0691 15.5642 28.0691 13.8621C28.0691 10.3455 25.481 8 21.5803 8H12V33H19.7254C25.5975 33 30 29.4073 30 24.6418C30 22.0317 28.6485 19.6878 26.253 18.1743ZM15.4767 11.252H21.1934C23.1244 11.252 24.3998 12.3487 24.3998 14.0127C24.3998 15.9033 22.7391 17.3407 19.3402 18.4374C17.0224 19.1553 15.98 19.7607 15.5932 20.4802L15.4767 20.4812V11.252ZM19.4162 29.748H15.4767V25.8907C15.4767 24.1886 16.9447 22.5246 18.9922 21.8811C20.8082 21.2758 22.3135 20.6704 23.5889 20.0285C25.2884 21.0127 26.3307 22.7132 26.3307 24.4913C26.3307 27.5166 23.3947 29.748 19.4162 29.748Z" />
                  </symbol>
                  <symbol id="brevo-bot" viewBox="0 0 24 22">
                    <path fill="#0B996E" d="M12 4a2 2 0 1 0 0-4 2 2 0 0 0 0 4ZM24 9a2 2 0 1 0-2 2v6a2 2 0 0 0 2-2V9ZM0 9c0-1.1.9-2 2-2v10a2 2 0 0 1-2-2V9Z" />
                    <path fill="#B3DFD2" d="M18 2H6a4 4 0 0 0-4 4v12a4 4 0 0 0 4 4h12a4 4 0 0 0 4-4V6a4 4 0 0 0-4-4Z" />
                    <path fill="none" stroke="#0B996E" strokeLinecap="round" strokeWidth="2" d="M6 16s.8 2 6 2 6-2 6-2" />
                    <path fill="#fff" stroke="#0B996E" strokeWidth="2" d="M12 13a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z" />
                  </symbol>
                  <symbol id="fa-check" viewBox="0 0 512 512">
                    <path d="M435.848 83.466L172.804 346.51l-96.652-96.652c-4.686-4.686-12.284-4.686-16.971 0l-28.284 28.284c-4.686 4.686-4.686 12.284 0 16.971l133.421 133.421c4.686 4.686 12.284 4.686 16.971 0l299.813-299.813c4.686-4.686 4.686-12.284 0-16.971l-28.284-28.284c-4.686-4.686-12.284-4.686-16.97 0z" />
                  </symbol>
                  <symbol id="fa-arrow-right" viewBox="0 0 448 512">
                    <path d="M218.101 38.101L198.302 57.9c-4.686 4.686-4.686 12.284 0 16.971L353.432 230H12c-6.627 0-12 5.373-12 12v28c0 6.627 5.373 12 12 12h341.432l-155.13 155.13c-4.686 4.686-4.686 12.284 0 16.971l19.799 19.799c4.686 4.686 12.284 4.686 16.971 0l209.414-209.414c4.686-4.686 4.686-12.284 0-16.971L235.071 38.101c-4.686-4.687-12.284-4.687-16.97 0z" />
                  </symbol>
                  <symbol id="fa-thumbs-up" viewBox="0 0 512 512">
                    <path d="M496.656 285.683C506.583 272.809 512 256 512 235.468c-.001-37.674-32.073-72.571-72.727-72.571h-70.15c8.72-17.368 20.695-38.911 20.695-69.817C389.819 34.672 366.518 0 306.91 0c-29.995 0-41.126 37.918-46.829 67.228-3.407 17.511-6.626 34.052-16.525 43.951C219.986 134.75 184 192 162.382 203.625c-2.189.922-4.986 1.648-8.032 2.223C148.577 197.484 138.931 192 128 192H32c-17.673 0-32 14.327-32 32v256c0 17.673 14.327 32 32 32h96c17.673 0 32-14.327 32-32v-8.74c32.495 0 100.687 40.747 177.455 40.726 5.505.003 37.65.03 41.013 0 59.282.014 92.255-35.887 90.335-89.793 15.127-17.727 22.539-43.337 18.225-67.105 12.456-19.526 15.126-47.07 9.628-69.405zM32 480V224h96v256H32zm424.017-203.648C472 288 472 336 450.41 347.017c13.522 22.76 1.352 53.216-15.015 61.996 8.293 52.54-18.961 70.606-57.212 70.974-3.312.03-37.247 0-40.727 0-72.929 0-134.742-40.727-177.455-40.727V235.625c37.708 0 72.305-67.939 106.183-101.818 30.545-30.545 20.363-81.454 40.727-101.817 50.909 0 50.909 35.517 50.909 61.091 0 42.189-30.545 61.09-30.545 101.817h111.999c22.73 0 40.627 20.364 40.727 40.727.099 20.363-8.001 36.375-23.984 40.727zM104 432c0 13.255-10.745 24-24 24s-24-10.745-24-24 10.745-24 24-24 24 10.745 24 24z" />
                  </symbol>
                  <symbol id="fa-thumbs-down" viewBox="0 0 512 512">
                    <path d="M496.656 226.317c5.498-22.336 2.828-49.88-9.627-69.405 4.314-23.768-3.099-49.377-18.225-67.105C470.724 35.902 437.75 0 378.468.014c-3.363-.03-35.508-.003-41.013 0C260.593-.007 195.917 40 160 40h-10.845c-5.64-4.975-13.042-8-21.155-8H32C14.327 32 0 46.327 0 64v256c0 17.673 14.327 32 32 32h96c17.673 0 32-14.327 32-32v-12.481c.85.266 1.653.549 2.382.856C184 320 219.986 377.25 243.556 400.82c9.9 9.9 13.118 26.44 16.525 43.951C265.784 474.082 276.915 512 306.91 512c59.608 0 82.909-34.672 82.909-93.08 0-30.906-11.975-52.449-20.695-69.817h70.15c40.654 0 72.726-34.896 72.727-72.571-.001-20.532-5.418-37.341-15.345-50.215zM128 320H32V64h96v256zm311.273-2.898H327.274c0 40.727 30.545 59.628 30.545 101.817 0 25.574 0 61.091-50.909 61.091-20.363-20.364-10.182-71.272-40.727-101.817-28.607-28.607-71.272-101.818-101.818-101.818H160V72.74h4.365c34.701 0 101.818-40.727 173.09-40.727 3.48 0 37.415-.03 40.727 0 38.251.368 65.505 18.434 57.212 70.974 16.367 8.78 28.538 39.235 15.015 61.996C472 176 472 224 456.017 235.648 472 240 480.1 256.012 480 276.375c-.1 20.364-17.997 40.727-40.727 40.727zM104 272c0 13.255-10.745 24-24 24s-24-10.745-24-24 10.745-24 24-24 24 10.745 24 24z" />
                  </symbol>
                  <symbol id="fa-redo" viewBox="0 0 512 512">
                    <path fill="currentColor" d="M500 8h-27.711c-6.739 0-12.157 5.548-11.997 12.286l2.347 98.568C418.075 51.834 341.788 7.73 255.207 8.001 118.82 8.428 7.787 120.009 8 256.396 8.214 393.181 119.165 504 256 504c63.926 0 122.202-24.187 166.178-63.908 5.113-4.618 5.354-12.561.482-17.433l-19.738-19.738c-4.498-4.498-11.753-4.785-16.501-.552C351.787 433.246 306.105 452 256 452c-108.322 0-196-87.662-196-196 0-108.322 87.662-196 196-196 79.545 0 147.941 47.282 178.675 115.302l-126.389-3.009c-6.737-.16-12.286 5.257-12.286 11.997V212c0 6.627 5.373 12 12 12h192c6.627 0 12-5.373 12-12V20c0-6.627-5.373-12-12-12z" />
                  </symbol>
                  <symbol id="icon-link" fill="none" viewBox="0 0 16 16">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6.667 8.667a3.333 3.333 0 0 0 5.026.36l2-2A3.333 3.333 0 0 0 8.98 2.313l-1.147 1.14" />
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9.333 7.333a3.333 3.333 0 0 0-5.026-.36l-2 2a3.333 3.333 0 0 0 4.713 4.714l1.14-1.14" />
                  </symbol>
                  <symbol id="Smile-icon" fill="none" viewBox="0 0 16 16">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 14.667A6.667 6.667 0 1 0 8 1.333a6.667 6.667 0 0 0 0 13.334z" />
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5.333 9.333s1 1.334 2.667 1.334c1.667 0 2.667-1.334 2.667-1.334M6 6h.007M10 6h.007" />
                  </symbol>
                  <symbol id="Send-icon" fill="none" viewBox="0 0 16 16">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M14.667 1.333 7.333 8.667m7.334-7.334L10 14.667l-2.667-6-6-2.667 13.334-4.667z" />
                  </symbol>
                  <symbol id="Paperclip-icon" fill="none" viewBox="0 0 16 17">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m14.293 8.367-6.126 6.126a4.002 4.002 0 1 1-5.66-5.66l6.126-6.126a2.668 2.668 0 1 1 3.774 3.773l-6.134 6.127a1.334 1.334 0 1 1-1.886-1.887l5.66-5.653" />
                  </symbol>
                  <symbol id="X-icon" fill="none" viewBox="0 0 16 16">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m12 4-8 8m0-8 8 8" />
                  </symbol>
                  <symbol id="AlertCircle-icon" fill="none" viewBox="0 0 16 16">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 14.667A6.667 6.667 0 1 0 8 1.333a6.667 6.667 0 0 0 0 13.334zm0-9.334V8m0 2.667h.007" />
                  </symbol>
                  <symbol id="ProgressiveIndicator-icon" fill="currentColor" viewBox="0 0 512 512">
                    <path d="m460.116 373.846-20.823-12.022c-5.541-3.199-7.54-10.159-4.663-15.874 30.137-59.886 28.343-131.652-5.386-189.946-33.641-58.394-94.896-95.833-161.827-99.676C261.028 55.961 256 50.751 256 44.352V20.309c0-6.904 5.808-12.337 12.703-11.982 83.556 4.306 160.163 50.864 202.11 123.677 42.063 72.696 44.079 162.316 6.031 236.832-3.14 6.148-10.75 8.461-16.728 5.01z" />
                  </symbol>
                  <symbol id="Star-icon" fill="none" viewBox="0 0 16 16">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m8 1.333 2.06 4.174 4.607.673-3.334 3.247.787 4.586L8 11.847l-4.12 2.166.787-4.586L1.333 6.18l4.607-.673L8 1.333z" />
                  </symbol>
                  <symbol id="RotateCw-icon" fill="none" viewBox="0 0 17 16">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15.333 2.667v4h-4" />
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13.66 10a6 6 0 1 1-1.413-6.24l3.086 2.907" />
                  </symbol>
                  <symbol id="ThumbsDown-icon" fill="none" viewBox="0 0 16 16">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M11.333 1.333h1.78a1.54 1.54 0 0 1 1.554 1.334v4.666a1.54 1.54 0 0 1-1.554 1.334h-1.78M6.667 10v2.667a2 2 0 0 0 2 2l2.666-6V1.333h-7.52A1.333 1.333 0 0 0 2.48 2.467l-.92 6A1.333 1.333 0 0 0 2.893 10h3.774z" />
                  </symbol>
                  <symbol id="ThumbsUp-icon" fill="none" viewBox="0 0 16 16">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4.667 14.667h-2a1.333 1.333 0 0 1-1.334-1.334V8.667a1.333 1.333 0 0 1 1.334-1.334h2M9.333 6V3.333a2 2 0 0 0-2-2l-2.666 6v7.334h7.52a1.334 1.334 0 0 0 1.333-1.134l.92-6A1.333 1.333 0 0 0 13.107 6H9.333z" />
                  </symbol>
                  <symbol id="Copy-icon" fill="none" viewBox="0 0 16 16">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13.333 6h-6C6.597 6 6 6.597 6 7.333v6c0 .737.597 1.334 1.333 1.334h6c.737 0 1.334-.597 1.334-1.334v-6c0-.736-.597-1.333-1.334-1.333z" />
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3.333 10h-.666a1.333 1.333 0 0 1-1.334-1.333v-6a1.333 1.333 0 0 1 1.334-1.334h6A1.333 1.333 0 0 1 10 2.667v.666" />
                  </symbol>
                  <symbol id="Check-icon" fill="none" viewBox="0 0 16 16">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13.333 4 6 11.333 2.667 8" />
                  </symbol>
                </defs>
              </svg>
              {" "}
              <svg className="box-content w-0 h-0 block absolute -top-25 -left-25 invisible overflow-hidden max-lg:hidden 2xl:hidden" data-ditto-id="style-span-16" fill="currentColor">
                <defs>
                  <symbol viewBox="0 0 16 16" fill="none">
                    <g>
                      <path d="M7.14493 0.417254C7.57924 -0.139085 8.42076 -0.139085 8.85507 0.417254L11.7223 4.09014C11.7769 4.1601 11.8399 4.22309 11.9099 4.2777L15.5827 7.14493C16.1391 7.57924 16.1391 8.42076 15.5827 8.85507L11.9099 11.7223C11.8399 11.7769 11.7769 11.8399 11.7223 11.9099L8.85507 15.5827C8.42076 16.1391 7.57924 16.1391 7.14493 15.5827L4.2777 11.9099C4.22309 11.8399 4.1601 11.7769 4.09014 11.7223L0.417254 8.85507C-0.139085 8.42076 -0.139085 7.57924 0.417254 7.14493L4.09014 4.2777C4.1601 4.22309 4.22309 4.1601 4.2777 4.09014L7.14493 0.417254Z" fill="url(#paint0_linear_1035_13349)" />
                      <path d="M7.14493 0.417254C7.57924 -0.139085 8.42076 -0.139085 8.85507 0.417254L11.7223 4.09014C11.7769 4.1601 11.8399 4.22309 11.9099 4.2777L15.5827 7.14493C16.1391 7.57924 16.1391 8.42076 15.5827 8.85507L11.9099 11.7223C11.8399 11.7769 11.7769 11.8399 11.7223 11.9099L8.85507 15.5827C8.42076 16.1391 7.57924 16.1391 7.14493 15.5827L4.2777 11.9099C4.22309 11.8399 4.1601 11.7769 4.09014 11.7223L0.417254 8.85507C-0.139085 8.42076 -0.139085 7.57924 0.417254 7.14493L4.09014 4.2777C4.1601 4.22309 4.22309 4.1601 4.2777 4.09014L7.14493 0.417254Z" fill="url(#paint1_radial_1035_13349)" />
                      <path d="M7.14493 0.417254C7.57924 -0.139085 8.42076 -0.139085 8.85507 0.417254L11.7223 4.09014C11.7769 4.1601 11.8399 4.22309 11.9099 4.2777L15.5827 7.14493C16.1391 7.57924 16.1391 8.42076 15.5827 8.85507L11.9099 11.7223C11.8399 11.7769 11.7769 11.8399 11.7223 11.9099L8.85507 15.5827C8.42076 16.1391 7.57924 16.1391 7.14493 15.5827L4.2777 11.9099C4.22309 11.8399 4.1601 11.7769 4.09014 11.7223L0.417254 8.85507C-0.139085 8.42076 -0.139085 7.57924 0.417254 7.14493L4.09014 4.2777C4.1601 4.22309 4.22309 4.1601 4.2777 4.09014L7.14493 0.417254Z" fill="url(#paint2_radial_1035_13349)" fillOpacity="0.3" />
                      <path d="M7.14493 0.417254C7.57924 -0.139085 8.42076 -0.139085 8.85507 0.417254L11.7223 4.09014C11.7769 4.1601 11.8399 4.22309 11.9099 4.2777L15.5827 7.14493C16.1391 7.57924 16.1391 8.42076 15.5827 8.85507L11.9099 11.7223C11.8399 11.7769 11.7769 11.8399 11.7223 11.9099L8.85507 15.5827C8.42076 16.1391 7.57924 16.1391 7.14493 15.5827L4.2777 11.9099C4.22309 11.8399 4.1601 11.7769 4.09014 11.7223L0.417254 8.85507C-0.139085 8.42076 -0.139085 7.57924 0.417254 7.14493L4.09014 4.2777C4.1601 4.22309 4.22309 4.1601 4.2777 4.09014L7.14493 0.417254Z" fill="url(#paint3_radial_1035_13349)" fillOpacity="0.6" />
                      <path d="M7.14493 0.417254C7.57924 -0.139085 8.42076 -0.139085 8.85507 0.417254L11.7223 4.09014C11.7769 4.1601 11.8399 4.22309 11.9099 4.2777L15.5827 7.14493C16.1391 7.57924 16.1391 8.42076 15.5827 8.85507L11.9099 11.7223C11.8399 11.7769 11.7769 11.8399 11.7223 11.9099L8.85507 15.5827C8.42076 16.1391 7.57924 16.1391 7.14493 15.5827L4.2777 11.9099C4.22309 11.8399 4.1601 11.7769 4.09014 11.7223L0.417254 8.85507C-0.139085 8.42076 -0.139085 7.57924 0.417254 7.14493L4.09014 4.2777C4.1601 4.22309 4.22309 4.1601 4.2777 4.09014L7.14493 0.417254Z" fill="url(#paint4_radial_1035_13349)" />
                    </g>
                    <g>
                      <path d="M5.77233 4.80112C6.75081 3.06629 9.24919 3.06629 10.2277 4.80112C10.4568 5.20735 10.7926 5.5432 11.1989 5.77233C12.9337 6.75081 12.9337 9.24919 11.1989 10.2277C10.7926 10.4568 10.4568 10.7926 10.2277 11.1989C9.24919 12.9337 6.75081 12.9337 5.77233 11.1989C5.5432 10.7926 5.20735 10.4568 4.80112 10.2277C3.06629 9.24919 3.06629 6.75081 4.80112 5.77233C5.20735 5.5432 5.5432 5.20735 5.77233 4.80112Z" fill="url(#paint5_linear_1035_13349)" />
                    </g>
                    <path d="M8.01799 6.28304C8.64278 5.60584 9.75202 6.24626 9.47794 7.12594C9.37868 7.4445 9.47173 7.79174 9.71696 8.01799C10.3942 8.64278 9.75374 9.75202 8.87406 9.47794C8.5555 9.37868 8.20826 9.47173 7.98201 9.71696C7.35722 10.3942 6.24798 9.75374 6.52206 8.87406C6.62132 8.5555 6.52827 8.20826 6.28304 7.98201C5.60584 7.35722 6.24626 6.24798 7.12594 6.52206C7.4445 6.62132 7.79174 6.52827 8.01799 6.28304Z" fill="white" />
                    <defs>
                      <linearGradient id="paint0_linear_1035_13349" x1="8" y1="4" x2="3" y2="4.5" gradientUnits="userSpaceOnUse">
                        <stop stopColor="#6358DE" />
                        <stop offset="1" stopColor="#4F46B2" />
                      </linearGradient>
                      <radialGradient id="paint1_radial_1035_13349" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(0.446038 6.45346) rotate(-28.8122) scale(15.7463 8.12778)">
                        <stop stopColor="#6358DE" />
                        <stop offset="1" stopColor="#6358DE" stopOpacity="0" />
                      </radialGradient>
                      <radialGradient id="paint2_radial_1035_13349" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(-0.237782 7.74512) rotate(-41.7295) scale(11.3009 3.05595)">
                        <stop offset="0.230133" stopColor="#DBD9F7" />
                        <stop offset="1" stopColor="#6358DE" stopOpacity="0" />
                      </radialGradient>
                      <radialGradient id="paint3_radial_1035_13349" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(12.3459 10.5512) rotate(5.99343) scale(9.18835 13.7751)">
                        <stop offset="0.300528" stopColor="#78BEFF" />
                        <stop offset="1" stopColor="#6358DE" stopOpacity="0" />
                      </radialGradient>
                      <radialGradient id="paint4_radial_1035_13349" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(1.47462 13.311) rotate(-30.5101) scale(8.41893 6.49565)">
                        <stop stopColor="#453E9B" />
                        <stop offset="0.791256" stopColor="#4F46B2" stopOpacity="0" />
                      </radialGradient>
                      <linearGradient id="paint5_linear_1035_13349" x1="8" y1="5.64634" x2="12" y2="11.5" gradientUnits="userSpaceOnUse">
                        <stop stopColor="#B3AEEF" />
                        <stop offset="1" stopColor="#BCDFFF" />
                      </linearGradient>
                    </defs>
                  </symbol>
                </defs>
              </svg>
              {" "}
              <div className="box-content h-full block overflow-hidden" id="f2-main">
                <div className="h-full block overflow-hidden" data-ditto-id="style-div-42">
                  <div className="box-content h-full flex relative z-15 flex-col overflow-hidden bg-primary shadow-[var(--clr-7)_0px_0px_10px_0px]">
                    <div className="box-content block shrink-0">
                      <button className="w-15 h-15 min-h-full block absolute top-0 left-0 z-18 max-w-15 leading-0 text-left bg-primary [animation-name:header-appear] [animation-duration:0.25s] [animation-timing-function:ease-out] [animation-fill-mode:both] cursor-pointer" data-component="button" aria-label="Discutez avec nous, nous sommes en ligne !" title="Discutez avec nous, nous sommes en ligne !" type="button">
                        <div className="inline-block max-w-full pr-[0.6875rem] pl-4 overflow-hidden align-top text-foreground whitespace-nowrap [overflow-wrap:normal] text-nowrap" aria-hidden="true">
                          {" "}
                          <span className="box-content hidden [overflow-wrap:break-word] before:content-[''] before:inline-block before:relative before:w-2 before:h-2 before:mr-0.5 before:bg-clr-8 before:shadow-[var(--clr-9)_0px_0px_0px_1px] before:rounded-tl-[5px]">
                            {" Discutez avec nous, nous sommes en ligne ! "}
                          </span>
                          {" "}
                          <svg className="box-content w-9 h-9 block absolute top-3 left-3 overflow-hidden [overflow-wrap:break-word] pointer-events-none" data-component="icon" aria-hidden="true" fill="currentColor">
                            <use xlinkHref="#chat-icon-bubble" />
                          </svg>
                          {" "}
                        </div>
                        {" "}
                      </button>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="block" data-ditto-id="style-ld-expand-28724" />
          </>
  );
}
