import "./ditto.css";
import Footer from "../sections/footer";
import Navbar from "../sections/navbar";
import DittoWire from "../ditto/DittoWire";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import ListRow3 from "./components/list-row3";
import ListRow4 from "./components/list-row4";
import ListRow5 from "./components/list-row5";
import ListRow6 from "./components/list-row6";
import ListRow7 from "./components/list-row7";
import ListRow8 from "./components/list-row8";
import ListRow9 from "./components/list-row9";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { href: "/formations/expert-ia", label: "Expert IA" },
    { href: "/formations/automatisation-n8n", label: "Automatisation & n8n" },
    { href: "/formations/robotique", label: "Robotique" },
    { href: "/formations/ia-recherche-sciences", label: "IA, Recherche & Sciences" }
];
const ListRow2_data = [
    { href: "/entreprises", label: "Entreprises" },
    { href: "/actualites", label: "Actualités" },
    { href: "/contact", label: "Contact" }
];
const ListRow3_data = [
    { href: "/entreprises", label: "Entreprises" },
    { href: "/actualites", label: "Actualités" },
    { href: "/contact", label: "Contact" }
];
const ListRow4_data = [
    { href: "/entreprises", label: "Entreprises" },
    { href: "/actualites", label: "Actualités" },
    { href: "/contact", label: "Contact" }
];
const ListRow5_data = [
    { text: "Lorsque vous exercez ce droit d'effacement, nous bloquons vos données personnelles pour tout type de traitement pendant la durée de conservation indiquée ci-dessus. Une fois ce délai écoulé, nous procédons à leur suppression définitive." },
    { text: "Droit à la limitation du traitement de vos données, ce qui signifie que dans certains cas vous pouvez nous demander d'en suspendre temporairement le traitement de vos données ou que nous les conservions au-delà du temps nécessaire si vous en avez besoin." },
    { text: "Droit de demander la portabilité de vos données personnelles. Cela signifie que vous aurez le droit de recevoir, dans un format structuré, couramment utilisé et lisible par machine, les données personnelles que vous nous avez fournies, afin de les transmettre directement à un autre responsable, lorsque cela est techniquement possible." },
    { text: "Vous pouvez également introduire une réclamation auprès de l'autorité de contrôle en matière de protection des données, auprès de l'autorité de contrôle compétente." }
];
const ListRow_data2 = [
    { href: "/formations/expert-ia", label: "Expert IA" },
    { href: "/formations/automatisation-n8n", label: "Automatisation & n8n" },
    { href: "/formations/robotique", label: "Robotique" },
    { href: "/formations/ia-recherche-sciences", label: "IA, Recherche & Sciences" }
];
const ListRow6_data = [
    { href: "/entreprises", label: "Entreprises" }
];
const ListRow7_data = [
    { href: "https://wa.me/243792369704", label: "WHATSAPP" },
    { href: "mailto:info@hoja-academy.com", label: "LINKEDIN" },
    { href: "https://hojanetwork.org", label: "HOJA NETWORK" },
    { href: "https://hojanetwork.org", label: "HOJA NETWORK" }
];
const ListRow8_data = [
    { ariacurrent: "page", href: "/confidentialite", label: "Politique de Confidentialité & Conditions" },
    { href: "/cookies", label: "Politique des Cookies" },
    { href: "/mentions-legales", label: "Mentions Légales" },
    { href: "/accessibilite", label: "Accessibilité" },
    { href: "/entreprises", label: "Entreprises" }
];
const ListRow9_data = [
    { ariacurrent: "page", href: "/confidentialite", label: "Politique de Confidentialité & Conditions" },
    { href: "/cookies", label: "Politique des Cookies" },
    { href: "/mentions-legales", label: "Mentions Légales" },
    { href: "/accessibilite", label: "Accessibilité" },
    { href: "/entreprises", label: "Entreprises" }
];
const ListRow_meta: string[][] = [
    ["interaction-sm-1767225603097025-2", "n22"],
    ["n23", "n24"],
    ["n25", "style-wp-submit"],
    ["n27", "n28"]
];
const ListRow2_meta: string[][] = [
    ["n29", "style-div"],
    ["style-div-18", "style-div-2"],
    ["style-div-19", "style-div-3"]
];
const ListRow3_meta: string[][] = [
    ["n56", "n57"],
    ["n58", "n59"],
    ["n60", "n61"]
];
const ListRow4_meta: string[][] = [
    ["n79", "n80"],
    ["n81", "n82"],
    ["n83", "n84"]
];
const ListRow5_meta: string[][] = [
    ["interaction-menu-1-516d334"],
    ["n170"],
    ["style-link-32"],
    ["interaction-li-2"]
];
const ListRow_meta2: string[][] = [
    ["n325", "style-div-90"],
    ["style-div-91", "n328"],
    ["n329", "n330"],
    ["n331", "n332"]
];
const ListRow6_meta: string[][] = [
    ["n333", "n334"],
    ["style-div-92", "n336"],
    ["n337", "style-svg-2"]
];
const ListRow7_meta: string[][] = [
    ["n351", "style-div-70", "style-div-71"],
    ["style-link-9", "style-not-started-5", "style-div-72"],
    ["n357", "n358", "n359"],
    ["n360", "n361", "n362"]
];
const ListRow8_meta: string[][] = [
    ["style-a-5", "n388"],
    ["style-span-44", "interaction-div-20"],
    ["n391", "n392"],
    ["n393", "n394"],
    ["n395", "n396"]
];
const ListRow9_meta: string[][] = [
    ["n401", "style-div-74"],
    ["n403", "n404"],
    ["n405", "n406"],
    ["n407", "n408"],
    ["n409", "n410"]
];
const ListRow_styles = [
    { className: "rounded-tl-[25px] rounded-tr-[25px]" },
    {  },
    {  },
    { className: "rounded-br-[25px] rounded-bl-[25px]" }
,
    { className: "" }];
const ListRow2_styles = [
    { className: "mx-[0.5px] 2xl:mx-[9.5px] after:right-[6.5625rem] 2xl:after:right-29.5" },
    { className: "mx-[0.5px] 2xl:mx-[9.5px] after:right-[6.0625rem] 2xl:after:right-[6.9375rem]" },
    { className: "ml-[0.5px] 2xl:ml-[9.5px] after:right-[5.0625rem] 2xl:after:right-[5.8125rem]" }
,
    { className: "" },
    { className: "" }];
const ListRow3_styles = [
    {  },
    {  },
    { className: "max-lg:rounded-br-[10px] max-lg:rounded-bl-[10px]" }
,
    { className: "" },
    { className: "" }];
const ListRow4_styles = [
    { className: "mx-[0.5px] 2xl:mx-[9.5px] after:right-[6.5625rem] 2xl:after:right-29.5" },
    { className: "mx-[0.5px] 2xl:mx-[9.5px] after:right-[6.0625rem] 2xl:after:right-[6.9375rem]" },
    { className: "ml-[0.5px] 2xl:ml-[9.5px] after:right-[5.0625rem] 2xl:after:right-[5.8125rem]" }
,
    { className: "" },
    { className: "" }];
const ListRow_styles2 = [
    { className: "rounded-tl-[15px] rounded-tr-[15px]" },
    {  },
    {  },
    { className: "rounded-br-[15px] rounded-bl-[15px]" }
,
    { className: "" }];
const ListRow6_styles = [
    { className: "mx-[17.5px] max-md:mx-[0.5625rem] 2xl:mx-[21.5px]" },
    { className: "mx-[17.5px] max-md:mx-[0.5625rem] 2xl:mx-[21.5px]" },
    { className: "ml-[17.5px] max-md:ml-[0.5625rem] 2xl:ml-[21.5px]" }
,
    { className: "" },
    { className: "" }];
const ListRow8_styles = [
    { className: "mr-[8.5px] 2xl:mr-[9.5px]" },
    { className: "mx-[8.5px] 2xl:mx-[9.5px]" },
    { className: "mx-[8.5px] 2xl:mx-[9.5px]" },
    { className: "mx-[8.5px] 2xl:mx-[9.5px]" },
    { className: "ml-[8.5px] 2xl:ml-[9.5px]" }
];
const ListRow9_styles = [
    { className: "mr-[8.5px] max-md:mr-[0.4375rem]" },
    { className: "mx-[8.5px] max-md:mx-[0.4375rem]" },
    { className: "mx-[8.5px] max-md:mx-[0.4375rem]" },
    { className: "mx-[8.5px] max-md:mx-[0.4375rem]" },
    { className: "ml-[8.5px] max-md:ml-[0.4375rem]" }
];

export const metadata = {
  title: 'Politique de confidentialité & conditions | HOJA ACADEMY',
  description: 'Traitement des données personnelles, conditions générales, garanties et politiques de remboursement HOJA ACADEMY.',
};
export default function Page() {
  return (
    <>
      {" "}
      <a className="w-px h-px block absolute -top-37500 left-0 -m-px overflow-hidden text-color-001 [font-family:Montserrat,_sans-serif] text-[0.9375rem] font-medium leading-[1.1875rem] [clip-path:inset(50%)] coursr-pointer" href="#content">
        Aller au contenu
      </a>
      {" "}
      <Navbar />
      {" "}
      <main className="block" id="content">
        {" "}
        <div className="block">
          <div className="block">
            <div className="min-h-[25.3125rem] flex relative max-w-full -mt-[7.0625rem] justify-center items-center gap-5 bg-color-001 bg-cover [background-position:50%_50%] bg-no-repeat max-md:min-h-[15.0625rem] max-md:-mt-22.5 max-md:px-[0.9375rem] max-md:flex-wrap max-md:justify-end md:max-lg:px-[3.3125rem] 2xl:-mt-33 2xl:pl-[13.8125rem]" style={{ backgroundImage: "url(\"/assets/cloned/images/6bfaf6f6a88b.png\")" }}>
              <div className="w-240 min-h-[16.3125rem] flex relative min-w-0 flex-col justify-end gap-5 max-md:w-[21.5625rem] max-md:min-h-41 max-md:flex-wrap md:max-lg:w-[569.3px] 2xl:w-[106.1875rem] 2xl:p-2.5">
                <div className="block relative min-w-0 max-w-full gap-5">
                  <div className="block">
                    <h1 className="block text-primary [font-family:Montserrat,_sans-serif] text-[2.625rem] font-bold leading-[6.3125rem] max-md:text-3xl max-md:leading-9 md:max-lg:leading-[3.125rem]" data-ditto-id="style-span-39" data-component="heading">
                      Politique de Confidentialité
                    </h1>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
            <div className="min-h-[44.8125rem] flex relative max-w-full py-16 px-[3.2rem] justify-center gap-5 max-md:pt-10 max-md:pb-5 max-md:px-5 max-md:flex-wrap md:max-lg:py-[2.4rem] md:max-lg:px-[30.7px] 2xl:py-24 2xl:px-[4.8rem]" data-ditto-id="style-section">
              <div className="w-4/5 block relative min-w-0 max-w-full gap-5 text-color-001 max-md:text-base max-md:leading-[1.3125rem]" data-ditto-id="style-div-83">
                <div className="h-full block" data-ditto-id="style-p-10">
                  <p className="block mb-[0.9rem]" data-ditto-id="style-heading-4">
                    Dans la présente Politique de Confidentialité, vous trouverez toutes les informations relatives à l'usage que nous faisons des données à caractère personnel que vous utilisez pour interagir avec nous en tant qu'utilisateur. Vous disposez de manière permanente de cette Politique de Confidentialité, que vous pouvez consulter chaque fois que vous le jugerez opportun.
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-div-84">
                    {"Si un doute vous vient à la lecture de ces informations, n'hésitez pas à nous poser une question par e-mail à l'adresse "}
                    <a className="inline [font-family:Montserrat,_sans-serif] text-lg font-medium leading-[1.1875rem]" data-ditto-id="style-span-40">
                      {"info@hoja-academy.com "}
                    </a>
                    .
                  </p>
                  {" "}
                  <h5 className="block mt-2 mb-4 font-medium leading-6 max-md:text-[1.25rem]" data-component="heading">
                    <span className="inline font-bold" data-ditto-id="interaction-span-11">
                      Qui sommes-nous ?
                    </span>
                  </h5>
                  {" "}
                  <p className="block mb-[0.9rem]">
                    HOJA ACADEMY, éditeur du site https://hoja-academy.com/, est responsable du traitement de vos données à caractère personnel, de leurs usages et de leur protection.
                  </p>
                  {" "}
                  <h5 className="block mt-2 mb-4 font-medium leading-6 max-md:text-[1.25rem]" data-ditto-id="style-section-2" data-component="heading">
                    <span className="inline font-bold" data-ditto-id="interaction-div-26">
                      Pour quelle finalité utilisons-nous vos données ?
                    </span>
                  </h5>
                  {" "}
                  <p className="block mb-[0.9rem]">
                    Selon la manière dont vous interagissez avec notre site web, nous traiterons vos données à caractère personnel pour les finalités suivantes :
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]">
                    Répondre aux consultations, suggestions ou demandes que vous nous adressez par le biais du site web.
                  </p>
                  {" "}
                  <h6 className="block mt-2 mb-4 text-base font-medium leading-[1.1875rem] max-md:[font-size:inherit]" data-ditto-id="style-p-6" data-component="heading">
                    <span className="inline text-xl font-bold leading-6">
                      Gestion académique et suivi de l'activité de l'élève
                    </span>
                  </h6>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-p-13">
                    Afin de garantir le bon déroulement des cours et la délivrance des certifications, HOJA ACADEMY enregistre l'activité sur le campus virtuel uniquement pour les utilisateurs inscrits en tant qu'apprenants de nos cours.
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-p-7">
                    Ces données incluent, entre autres, la progression dans les leçons, les temps de connexion et la finalisation des activités.
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]">
                    Le traitement est effectué conformément à l'art. 6.1.b) du RGPD (exécution du contrat de formation) et les données ne sont conservées que pendant le temps nécessaire à la gestion académique et aux obligations légales associées.
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-div-101">
                    En aucun cas la navigation des visiteurs anonymes qui ne sont pas des élèves n'est surveillée.
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]">
                    <strong className="inline font-bold">
                      Gestion du Entreprises
                    </strong>
                    <span className="inline" aria-hidden="true" />
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]">
                    Si vous demandez à participer au Entreprises de HOJA ACADEMY, nous traiterons vos données personnelles aux fins de gérer votre demande, d'approuver ou de refuser votre participation, d'administrer votre compte affilié, d'assurer le suivi des visites et des ventes attribuées à vos liens ou coupons, de calculer les commissions générées, de gérer les paiements correspondants et de prévenir les utilisations frauduleuses ou contraires aux conditions du Programme.
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-p-14" />
                  {" "}
                  <p className="block mb-[0.9rem]">
                    Le traitement sera effectué principalement sur la base de l'exécution de la relation contractuelle découlant de votre participation au Entreprises et, le cas échéant, pour le respect des obligations légales applicables.
                  </p>
                  {" "}
                  <h5 className="block mt-2 mb-4 font-medium leading-6 max-md:text-[1.25rem]" data-ditto-id="style-p-11" data-component="heading">
                    <span className="inline font-bold" data-ditto-id="style-p-8">
                      Quelles données à caractère personnel vous demanderons-nous ?
                    </span>
                  </h5>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-p-9">
                    Par le biais de notre formulaire de contact : Nom, adresse e-mail et téléphone.
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="interaction-p">
                    Dans la Politique relative aux cookies, vous trouverez quel autre type d'informations nous recueillerons par le biais de l'utilisation des cookies.
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-p-12">
                    Rappelez-vous que toutes les données que nous vous demandons à titre obligatoire sont les données minimales nécessaires pour pouvoir vous fournir le service ou vous permettre l'accès à une fonctionnalité déterminée du site web.
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-p-4">
                    <strong className="inline font-bold" data-ditto-id="interaction-p-2">
                      Dans le cas du Entreprises :
                    </strong>
                    {" nous pourrons demander le nom et le prénom, l'adresse e-mail, le nom d'utilisateur, des informations sur la manière dont vous allez promouvoir HOJA ACADEMY, le site web ou le canal de promotion lorsqu'il est fourni, ainsi que l'adresse e-mail associée au moyen de paiement sélectionné, par exemple PayPal."}
                    <span className="inline" data-ditto-id="interaction-p-3" aria-hidden="true" />
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="interaction-button" />
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="interaction-span-3">
                    De même, durant votre participation au Programme, nous pourrons enregistrer des informations relatives aux visites, aux parrainages, aux ventes attribuées, aux commissions générées et aux paiements effectués.
                  </p>
                  {" "}
                  <h5 className="block mt-2 mb-4 font-medium leading-6 max-md:text-[1.25rem]" data-ditto-id="style-p" data-component="heading">
                    <span className="inline font-bold" data-ditto-id="interaction-link">
                      Pourquoi utilisons-nous vos données ?
                    </span>
                  </h5>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="interaction-span-4">
                    La légitimation du traitement de vos données provient du fait que nous avons besoin de les traiter pour exécuter le contrat que vous acceptez avec nous lors de votre inscription et lors de la jouissance de nos services ou fonctionnalités.
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-navegaci-n-entre-noticias-del-d-a">
                    Il existe d'autres raisons, telles que notre intérêt à répondre à vos consultations ou demandes et le consentement que vous nous accordez pour que nous puissions vous envoyer nos informations commerciales.
                  </p>
                  {" "}
                  <h5 className="block mt-2 mb-4 font-medium leading-6 max-md:text-[1.25rem]" data-ditto-id="style-link-7" data-component="heading">
                    <span className="inline font-bold" data-ditto-id="style-br-3">
                      Combien de temps conservons-nous vos données ?
                    </span>
                  </h5>
                  {" "}
                  <p className="block mb-[0.9rem]">
                    {"Vos données à caractère personnel seront conservées pendant le temps où votre compte utilisateur restera actif. Rappelez-vous que vous pouvez le supprimer à tout moment par une demande adressée à l'adresse e-mail "}
                    <a className="inline [font-family:Montserrat,_sans-serif] text-lg font-medium leading-[1.1875rem]">
                      {"info@hoja-academy.com "}
                    </a>
                    . Une fois le compte supprimé, vos données à caractère personnel seront conservées bloquées pendant la période exigée par la législation fiscale pour la prescription des responsabilités au cas où vous auriez effectué une acquisition de produits.
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]">
                    Dans tout autre cas, vos données à caractère personnel seront conservées pendant une période de 3 mois à compter de votre décision de suppression, au cas où des responsabilités pourraient en découler.
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]">
                    Une fois les délais écoulés, les données seront supprimées de nos registres.
                  </p>
                  {" "}
                  <div className="block" data-ditto-id="style-br-2">
                    <p className="block mb-[0.9rem]" data-ditto-id="interaction-br">
                      <span className="inline font-bold">
                        Avec qui partageons-nous vos données ?
                      </span>
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-br">
                      Pour la réalisation des finalités énoncées, vos données à caractère personnel seront communiquées à des prestataires de services auxiliaires qui facilitent notre gestion ou l'accomplissement de nos obligations légales, tels que, entre autres, des sociétés de transport, de conseil fiscal et juridique et d'hébergement web.
                      <span className="inline" data-ditto-id="interaction-span" aria-hidden="true" />
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      Dans le cas des affiliés, les données strictement nécessaires à la gestion du paiement des commissions pourront être communiquées au fournisseur de services de paiement utilisé, comme PayPal, aux seules fins d'effectuer lesdits paiements.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      {"En utilisant la fonction IA « Alvi », vous acceptez que des données vocales, leurs transcriptions et métadonnées (date, heure, durée) soient collectées et traitées afin de faciliter la communication en temps réel et de garantir la sécurité du service. La base légale de ce traitement est l'exécution du contrat et votre consentement exprès ; les données sont conservées pendant la durée nécessaire conformément à la réglementation en vigueur. Vous pourrez exercer vos droits d'accès, de rectification, d'effacement, de portabilité et d'opposition en envoyant une demande à "}
                      <a className="inline [font-family:Montserrat,_sans-serif] text-[0.9375rem] font-medium leading-[1.1875rem] coursr-pointer" data-ditto-id="style-span-47" data-component="link" href="mailto:info@hoja-academy.com" rel="noopener">
                        info@hoja-academy.com
                      </a>
                      .
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      Nous céderons également vos données à caractère personnel à des Organismes ou Administrations publics auxquels nous sommes tenus par une exigence légale.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" />
                    <p className="block mb-[0.9rem]" data-ditto-id="style-p-15">
                      {"Vous pouvez demander la liste de ces sociétés et organismes par le biais de notre adresse e-mail "}
                      <a className="inline [font-family:Montserrat,_sans-serif] text-[0.9375rem] font-medium leading-[1.1875rem] coursr-pointer" data-ditto-id="style-footer-3" data-component="link" href="mailto:info@hoja-academy.com" rel="noopener">
                        info@hoja-academy.com
                      </a>
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      <span className="inline font-bold" data-ditto-id="interaction-div-7">
                        Quels droits avez-vous sur vos données à caractère personnel ?
                      </span>
                    </p>
                    {" "}
                  </div>
                  {" "}
                  <div className="block">
                    <p className="block mb-[0.9rem]" data-ditto-id="interaction-div-6">
                      {"Indépendamment de la base juridique sur laquelle nous avons effectué le traitement de vos données à caractère personnel, vous disposez d'un ensemble de droits que vous pouvez exercer, par communication à l'adresse e-mail "}
                      <a className="inline [font-family:Montserrat,_sans-serif] text-lg font-medium leading-[1.1875rem]" data-ditto-id="interaction-div-8">
                        {"info@hoja-academy.com "}
                      </a>
                      .
                    </p>
                    {" "}
                    <ul className="block pl-10 [list-style-type:disc] list-outside bg-background max-md:text-[1.25rem]" data-ditto-id="style-menu-2">
                      {ListRow5_data.map((d, i) => <ListRow5 key={i} d={d} />)}
                    </ul>
                    {" "}
                    <div className="block" data-ditto-id="interaction-sm-17672256027865476-1" />
                    {" "}
                    <div className="block" data-ditto-id="style-span-6">
                      <h5 className="block mt-2 mb-4 font-medium leading-6 max-md:text-[1.25rem]" data-ditto-id="style-icon-2" data-component="heading">
                        <span className="inline font-bold" data-ditto-id="interaction-sm-17672256027865476-2">
                          Modifications de la Politique de Confidentialité
                        </span>
                      </h5>
                      {" "}
                      <p className="block mb-[0.9rem]">
                        Nous pourrons adapter ou modifier les informations contenues dans la présente Politique de Confidentialité lorsque nous le jugerons opportun, ou intégrer de nouvelles fonctionnalités sur la plateforme qui l'exigent.
                      </p>
                      {" "}
                      <p className="block mb-[0.9rem]">
                        En caso de que lo hagamos, te lo notificaremos mediante un banner informativo en la propia web.
                      </p>
                      {" "}
                      <p className="block mb-[0.9rem]" data-ditto-id="style-p-2">
                        Nous vous conseillons de vérifier périodiquement la présente Politique de Confidentialité.
                      </p>
                      {" "}
                      <h3 className="block mt-2 mb-4 text-[1.6875rem] font-medium leading-[2.6875rem]" data-ditto-id="style-b-5" data-component="heading">
                        <span className="inline font-bold">
                          CONDITIONS GÉNÉRALES DE CONTRACTATION
                        </span>
                      </h3>
                      {" "}
                    </div>
                    {" "}
                    <div className="block" data-ditto-id="style-ul">
                      <p className="block mb-[0.9rem]" data-ditto-id="interaction-li-3">
                        L'utilisation des services du Site Web, ainsi que l'acquisition de l'un des produits proposés, implique votre acceptation, en tant que Client, sans réserve d'aucune sorte, de toutes les stipulations contenues dans les présentes Conditions Générales.
                      </p>
                      {" "}
                      <p className="block mb-[0.9rem]" data-ditto-id="style-b">
                        Votre inscription au site web et l'utilisation de ses services impliquent que les données à caractère personnel que vous avez fournies feront partie de fichiers destinés à leur traitement, selon les finalités, légitimations, cessions et durées de conservation détaillées dans la Politique de Confidentialité.
                      </p>
                      {" "}
                      <h5 className="block mt-2 mb-4 font-medium leading-6 max-md:text-[1.25rem]" data-ditto-id="style-li-2" data-component="heading">
                        <span className="inline font-bold" data-ditto-id="interaction-b-2">
                          Limitaciones
                        </span>
                      </h5>
                      {" "}
                      <p className="block mb-[0.9rem]" data-ditto-id="style-li">
                        Le contenu promotionnel du site web s'adresse à tous les utilisateurs, mais si vous souhaitez vous inscrire en tant que client ou effectuer un achat, vous devez être majeur.
                      </p>
                      {" "}
                      <h5 className="block mt-2 mb-4 font-medium leading-6 max-md:text-[1.25rem]" data-ditto-id="style-b-3" data-component="heading">
                        <span className="inline font-bold">
                          Garantie et Politique de Remboursement
                        </span>
                      </h5>
                      {" "}
                      <p className="block mb-[0.9rem]">
                        Le Programme Intensif d'IA Générative comprend une garantie de remboursement de 7 jours calendaires à compter du premier jour de cours en direct.
                      </p>
                      {" "}
                      <p className="block mb-[0.9rem]" data-ditto-id="interaction-div-5">
                        Les cours de la gamme « Expert en... » incluent également une garantie de remboursement de 7 jours calendaires à compter de l'accès au contenu du cours, tant que l'apprenant n'a pas progressé au-delà de la première leçon du cours (laquelle comprend environ 4 à 5 thèmes selon le cours concerné).
                      </p>
                      {" "}
                      <p className="block mb-[0.9rem]" data-ditto-id="interaction-div-3">
                        Cette garantie permet à l'élève d'accéder au contenu, de le parcourir et d'évaluer si le cours correspond à ses besoins.
                      </p>
                      {" "}
                      <p className="block mb-[0.9rem]" data-ditto-id="style-div-16">
                        Une fois le délai indiqué écoulé ou les conditions d'utilisation mentionnées dépassées, le remboursement du montant versé ne sera pas dû.
                      </p>
                      {" "}
                      <h5 className="block mt-2 mb-4 font-medium leading-6 max-md:text-[1.25rem]" data-ditto-id="style-div-15" data-component="heading">
                        <b className="inline font-bold" data-ditto-id="interaction-div-4">
                          Réservation de places dans les formations
                        </b>
                      </h5>
                      {" "}
                      <div className="block">
                        <p className="block mb-[0.9rem]" data-ditto-id="style-link-5">
                          Dans certaines formations, HOJA ACADEMY pourra offrir la possibilité de réserver une place moyennant le paiement anticipé d'un montant déterminé.
                        </p>
                        <p className="block mb-[0.9rem]">
                          Le montant versé pour la réservation sera intégralement déduit du prix final de la formation. Avant le paiement, le client est informé du prix total applicable, du montant de la réservation, du solde à régler, de la date de début de la formation et de la date limite de règlement.
                        </p>
                        <p className="block mb-[0.9rem]">
                          Si le client ne s'acquitte pas du montant restant dans le délai indiqué, HOJA ACADEMY pourra annuler la réservation et libérer la place.
                        </p>
                        <p className="block mb-[0.9rem]" data-ditto-id="style-div-10">
                          {"Lorsque la souscription est effectuée à distance par un consommateur, ce dernier bénéficiera du droit de rétractation prévu par la loi pendant "}
                          <strong className="inline font-bold" data-ditto-id="style-div-94">
                            14 jours calendaires à compter de la conclusion du contrat
                          </strong>
                          {", sauf exceptions prévues par la législation applicable. "}
                        </p>
                        <p className="block mb-[0.9rem]">
                          Une fois le délai de rétractation écoulé, si le client décide volontairement d'annuler sa participation ou ne procède pas au paiement dans le délai établi, le montant versé à titre de réservation pourra être retenu en compensation de la place réservée, dans les limites autorisées par la législation applicable.
                        </p>
                        <p className="block mb-[0.9rem]">
                          Si HOJA ACADEMY annule la formation et qu'aucun accord n'est conclu avec le client pour reporter la réservation sur une autre édition, le montant versé sera intégralement remboursé.
                        </p>
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <h5 className="block mt-2 mb-4 font-medium leading-6 max-md:text-[1.25rem]" data-ditto-id="interaction-b" data-component="heading">
                      <span className="inline font-bold">
                        Accès au Contenu
                      </span>
                    </h5>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-b-2">
                      L'élève aura accès au contenu du cours pour une durée indéterminée, sans limite de temps, tant que la plateforme et le service resteront actifs.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="interaction-li">
                      HOJA ACADEMY s'engage à maintenir l'accès au contenu et sa disponibilité dans des conditions normales de fonctionnement.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-b-6">
                      Toutefois, dans des circonstances exceptionnelles indépendantes de sa volonté, telles que pannes techniques graves, cyberattaques, cas de force majeure, fermeture de la plateforme, changements structurels du service ou toute autre situation échappant à son contrôle raisonnable, l'accès permanent ou à vie au contenu n'est pas garanti.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-li-5">
                      En cas d'incident majeur, des efforts raisonnables seront déployés pour rétablir l'accès ou fournir une solution alternative lorsque cela est possible.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-b-7">
                      L'acquisition du cours confère à l'élève une licence d'accès au contenu, non la propriété de celui-ci.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-li-4" />
                    {" "}
                    <h5 className="block mt-2 mb-4 font-medium leading-6 max-md:text-[1.25rem]" data-ditto-id="style-b-4" data-component="heading">
                      <span className="inline font-bold">
                        Modification des Contenus et de l'Organisation
                      </span>
                    </h5>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-footer" />
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-div-95">
                      HOJA ACADEMY se réserve le droit de mettre à jour, de modifier ou d'améliorer les contenus, outils, structure, méthodologie ou calendrier des cours afin de les adapter aux avancées technologiques, aux améliorations pédagogiques ou aux besoins organisationnels.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      Dans le cas des cours en direct, des changements de date, d'horaire ou d'enseignant peuvent se produire pour des causes justifiées, l'organisation s'engageant à les communiquer avec la plus grande antériorité possible et à offrir une solution alternative lorsque cela est nécessaire.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="interaction-div-2">
                      Ces modifications ne donneront pas droit à remboursement, dès lors qu'elles n'altèrent pas de manière substantielle la nature du programme de formation souscrit.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-link-2" />
                    {" "}
                    <h5 className="block mt-2 mb-4 font-medium leading-6 max-md:text-[1.25rem]" data-ditto-id="style-span-2" data-component="heading">
                      <span className="inline font-bold" data-ditto-id="interaction-span-2">
                        Exonération de Responsabilité concernant les Résultats
                      </span>
                    </h5>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-icon-3" />
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-span-46">
                      Les cours proposés par HOJA ACADEMY ont un caractère formatif et éducatif.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      HOJA ACADEMY ne garantit pas l'obtention de résultats économiques, professionnels ou empresariaux spécifiques découlant de l'application des connaissances acquises.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="interaction-div">
                      L'élève reconnaît que la mise en œuvre de ce qui est appris dépend de facteurs individuels, du contexte professionnel et de l'investissement personnel, de sorte que les résultats peuvent varier dans chaque cas.
                    </p>
                    {" "}
                    <div className="block">
                      <h5 className="block mt-2 mb-4 font-medium leading-6 max-md:text-[1.25rem]" data-ditto-id="style-link-4" data-component="heading">
                        <span className="inline font-bold" data-ditto-id="interaction-image">
                          Protection des Contenus et Interdiction de Téléchargement, de Distribution et de Commercialisation
                        </span>
                      </h5>
                      {" "}
                    </div>
                    {" "}
                    <div className="block" data-ditto-id="style-div-102">
                      {" L'utilisateur reconnaît et accepte que tous les contenus audiovisuels, supports pédagogiques, enregistrements de cours (en direct par visioconférence ou enregistrés) et tout autre support mis à disposition via la plateforme constituent des œuvres protégées par les droits de propriété intellectuelle de HOJA ACADEMY et sont couverts par la la législation applicable en matière de propriété intellectuelle. Sauf autorisation préalable et écrite de HOJA ACADEMY, sont expressément interdits :"}
                    </div>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-div-96">
                      •Télécharger, copier, reproduire, distribuer, communiquer publiquement ou transformer totalement ou partiellement lesdits contenus.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-div-22">
                      •Commercialiser, céder ou mettre à disposition de tiers, que ce soit gratuitement ou en échange d'une quelconque rémunération, les contenus mentionnés.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-p-3">
                      •Partager les identifiants de connexion ou faciliter l'accès à des personnes non inscrites au cours.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-strong">
                      Le non-respect de l'une de ces obligations sera considéré comme une infraction grave, autorisant HOJA ACADEMY à engager les actions légales appropriées, notamment la demande de mesures conservatoires, la réclamation de dommages et intérêts et, le cas échéant, la plainte pénale conformément à la législation en vigueur. HOJA ACADEMY se réserve le droit de surveiller et d'auditer l'utilisation de la plateforme afin de prévenir et détecter toute activité illicite ou contraire aux stipulations de la présente clause.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="interaction-div-22" />
                    {" "}
                    <h5 className="block mt-2 mb-4 font-medium leading-6 max-md:text-[1.25rem]" data-ditto-id="style-div-103" data-component="heading">
                      <span className="inline font-bold" data-ditto-id="style-div-5">
                        Suspension ou Annulation de l'Accès
                      </span>
                    </h5>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-div-6" />
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-menu">
                      HOJA ACADEMY se réserve le droit de suspendre ou d'annuler l'accès au campus virtuel des élèves qui ne respecteraient pas les présentes conditions, feraient un usage abusif de la plateforme, partageraient leurs identifiants de connexion ou violeraient des droits de propriété intellectuelle.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      La suspension pourra être effectuée de manière immédiate et sans droit à remboursement lorsque le manquement est grave ou répété.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-div-17" />
                    {" "}
                    <h5 className="block mt-2 mb-4 font-medium leading-6 max-md:text-[1.25rem]" data-ditto-id="style-image" data-component="heading">
                      <span className="inline font-bold">
                        Utilisation Appropriée de la Plateforme
                      </span>
                    </h5>
                    {" "}
                    <p className="block mb-[0.9rem]" />
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-div-97">
                      L'élève s'engage à utiliser le campus virtuel, les forums, les visioconférences et les autres ressources de formation de manière respectueuse et conforme à la loi.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      La publication de contenus offensants, illégaux, promotionnels non autorisés ou pouvant affecter négativement le déroulement normal du cours ou d'autres élèves ne sera pas permise.
                    </p>
                    {" "}
                    <h5 className="block mt-2 mb-4 font-medium leading-6 max-md:text-[1.25rem]" data-ditto-id="style-div-27" data-component="heading">
                      <span className="inline font-bold">
                        Législation Applicable et Juridiction
                      </span>
                    </h5>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-heading-2">
                      Les deux clauses, ainsi que tout litige pouvant découler de leur interprétation, de leur exécution ou de leur réalisation, seront régies et interprétées conformément à la législation applicable et, pour ce qui n'est pas prévu, à la réglementation de l'Union européenne.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-link-6">
                      Pour la résolution de tout litige, les parties s’efforceront de trouver une solution amiable ; à défaut, la juridiction compétente sera désignée par la législation applicable.
                    </p>
                    {" "}
                    <h5 className="block mt-2 mb-4 font-medium leading-6 max-md:text-[1.25rem]" data-ditto-id="style-div-7" data-component="heading">
                      <span className="inline font-bold" data-ditto-id="style-div-98">
                        CONDITIONS GÉNÉRALES DU PROGRAMME D'AFFILIATION DE HOJA ACADEMY
                      </span>
                    </h5>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      <span className="inline font-bold" data-ditto-id="style-menu-1-74a24f8">
                        1. Acceptation de l'Accord
                      </span>
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      En qualité d'affilié autorisé (ci-après, l’« Affilié ») de HOJA ACADEMY, vous vous engagez à respecter intégralement les termes et conditions du présent Accord. Il est essentiel d'en lire attentivement le contenu avant de vous inscrire et de commencer à promouvoir HOJA ACADEMY. Votre participation au Programme a pour seule finalité la publicité licite de notre site web, par laquelle vous pourrez percevoir une commission sur les inscriptions et produits acquis par des tiers adressés à HOJA ACADEMY par votre propre site web ou par recommandations personnelles. En vous inscrivant au Programme, vous acceptez de manière expresse et contraignante chacune des dispositions contenues dans le présent document.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      <span className="inline font-bold">
                        2. Approbation ou Rejet de la Demande
                      </span>
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      HOJA ACADEMY se réserve le droit, à son entière et absolue discrétion, d'approuver ou de rejeter toute demande d'adhésion au Programme. La décision de rejet ne générera aucun droit à réclamation ou recours légal de la part du demandeur.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-div-99">
                      <span className="inline font-bold">
                        3. Commissions
                      </span>
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      •Les commissions seront versées mensuellement, dès lors que le compte parrainé restera actif pendant un minimum de 31 jours.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-span-4">
                      •L'auto-promotion ne sera pas autorisée et aucune commission ne sera versée sur des comptes propres.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-icon-4">
                      •Seules les transactions dûment finalisées donneront lieu au versement de commissions ; celles donnant lieu à des rétrofacturations ou à des remboursements seront exclues du paiement.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-div-11">
                      <span className="inline font-bold" data-ditto-id="style-div-21">
                        3.1. Conditions Spéciales de Paiement selon le Type de Cours
                      </span>
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-div-100">
                      {"•Para los "}
                      <span className="inline font-bold" data-ditto-id="style-div-13">
                        cours spécialisés
                      </span>
                      , le paiement de la commission correspondante sera effectué une fois écoulés 32 jours, pour autant que l'élève concerné n'ait pas demandé de restitution, d'annulation ou de remboursement durant cette période.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      {"•Para los "}
                      <span className="inline font-bold">
                        cours dispensés par visioconférence
                      </span>
                      , le paiement sera effectué à 7 jours à compter du début du cours, ce délai étant considéré comme la période d'essai aux fins de la demande de restitution. Si une restitution intervient durant ce délai, la commission correspondante sera annulée ou déduite du paiement lors du cycle suivant.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-gt-wrapper-56609209">
                      <span className="inline font-bold" data-ditto-id="style-english">
                        4. Résiliation
                      </span>
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-spanish">
                      HOJA ACADEMY pourra suspendre ou mettre fin, à tout moment et sans préavis, à la qualité d'Affilié, dans les cas suivants, entre autres :
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      •Publicité inappropriée, incluant des déclarations fausses, des hyperliens trompeurs ou d'autres pratiques induisant en erreur.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-div-4">
                      •Envoi massif de courriels, publications sur des forums ou toute autre forme de spam.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      •Publicité sur des sites qui promeuvent des activités illégales ou contraires à l'ordre public.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      •Non-respect de la divulgation de la relation d'affiliation lorsque la réglementation applicable en vigueur en Espagne et dans l'Union européenne l'exige.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-div-89">
                      •Violation des droits de propriété intellectuelle, y compris l'utilisation abusive des marques déposées de HOJA ACADEMY, pouvant nécessiter, le cas échéant, la formalisation d'accords de licence pour leur utilisation.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      •Offrir des remboursements, des coupons ou d'autres incitations dérivés de la commission comme incitation à l'acquisition, sauf s'il s'agit de remises ou de promotions autorisées et préalablement définies.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      •Referencias a cuentas propias, transacciones fraudulentas o toute activité suspecte de fraude dans le cadre du Programme.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-image-5">
                      En tout état de cause, HOJA ACADEMY se réserve le droit de clôturer le compte de l'Affilié sans avoir à justifier sa décision, cette résiliation prenant effet immédiatement.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-iframe-2">
                      <span className="inline font-bold" data-ditto-id="style-svg-3">
                        5. Liens d'affiliation et matériel publicitaire
                      </span>
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      L'Affilié pourra utiliser aussi bien des liens graphiques que textuels sur son site web, dans ses e-mails et autres supports, en ligne comme hors ligne (annonces classées, revues, journaux, etc.), pour autant que ces matériaux respectent les conditions établies dans le présent Accord. Il pourra utiliser le matériel graphique et textuel fourni par HOJA ACADEMY ou créer le sien, pourvu qu'il soit approprié, ne soit pas trompeur et respecte les conditions prévues ici.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      <span className="inline font-bold">
                        6. Coupons et sites de bons plans
                      </span>
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      HOJA ACADEMY peut, à certaines occasions, proposer des coupons ou réductions à des affiliés préapprouvés ou aux abonnés de notre newsletter. À défaut d'approbation ou d'attribution d'un coupon de marque, l'Affilié n'est pas autorisé à promouvoir des coupons ou réductions relatifs à HOJA ACADEMY.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      L'Affilié s'engage à :
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      •Ne pas utiliser de textes ou de graphiques trompeurs dans ses liens, boutons ou images pouvant induire en erreur sur la disponibilité ou les conditions des offres autorisées.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-svg">
                      •S'abstenir d'enchérir sur des termes liés à « HOJA ACADEMY Coupons », « HOJA ACADEMY Réductions » ou à d'autres expressions pouvant induire l'utilisateur en erreur sur l'existence de coupons officiels.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-f2-main">
                      •Ne pas générer de fenêtres surgissantes, de cadres (iframes, frames) ou d'autres actions qui installent des cookies d'affiliation sans le consentement exprès de l'utilisateur, qui doit pouvoir visualiser les informations complètes sur l'offre avant que le lien d'affiliation ne s'active.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-div-14">
                      •Éviter toute formulation textuelle du type « Cliquez pour voir les offres/coupons » en l'absence d'offres autorisées, étant motif d'exclusion immédiate du Programme en cas de manquement.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="interaction-div-24">
                      <span className="inline font-bold">
                        7. Politique de Paiement au Clic (PPC)
                      </span>
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-chatea-con-nosotros-estamos-online">
                      La réalisation d'enchères par le biais de systèmes de Paiement au Clic (PPC) sur des moteurs de recherche ou d'autres plateformes publicitaires n'est pas autorisée sans l'autorisation préalable et écrite de HOJA ACADEMY.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="interaction-div-25">
                      <span className="inline font-bold">
                        8. Responsabilidad
                      </span>
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      HOJA ACADEMY ne sera pas responsable des dommages indirects ou accidentels pouvant découler du fonctionnement du Programme ou du site web.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-div-39">
                      Le Programme est fourni « en l'état » et sans garanties expresses ou implicites quant à son fonctionnement, un fonctionnement ininterrompu ou exempt d'erreurs n'étant pas assuré, HOJA ACADEMY étant exonéré de toute responsabilité en cas d'éventuelles interruptions ou défaillances.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      <span className="inline font-bold">
                        9. Durée de l'Accord
                      </span>
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-gt-wrapper-28246617">
                      Le présent Accord entre en vigueur à compter de l'acceptation de l'Affilié au Programme et restera en vigueur jusqu'à la clôture de son compte affilié. HOJA ACADEMY se réserve le droit de modifier les termes et conditions du présent Accord à tout moment ; la poursuite de la participation au Programme après de telles modifications vaudra acceptation de celles-ci. En cas de désaccord avec les modifications, l'Affilié devra mettre fin à sa participation.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-div-8">
                      <span className="inline font-bold" data-ditto-id="style-div-9">
                        10. Indemnisation
                      </span>
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-menu-3">
                      L'Affilié indemnisera et tiendra indemnes HOJA ACADEMY ainsi que ses sociétés affiliées, dirigeants, salariés, licenciés, ayants droit et cessionnaires de toute réclamation, dommage, amende, coût ou dépense (y compris les honoraires d'avocat raisonnables) découlant d'une négligence, d'une déclaration inexacte, d'une omission d'information ou d'une conduite frauduleuse de l'Affilié en relation avec le présent Accord.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      <span className="inline font-bold" data-ditto-id="style-div-41">
                        11. Signature Électronique et Caractère Contractuel
                      </span>
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-image-4">
                      Le présent Accord constitue un contrat électronique légalement contraignant. En complétant la demande et en s'inscrivant au Entreprises de HOJA ACADEMY, l'Affilié manifeste son consentement et son acceptation du présent Accord, cet acte valant signature électronique ayant la même valeur et le même effet qu'une signature manuscrite.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      <span className="inline font-bold">
                        12. Législation Applicable et Juridiction
                      </span>
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-div-31">
                      Le présent Accord est régi et interprété conformément à la législation applicable et, pour ce qui en est applicable, à la réglementation de l'Union européenne. Pour la résolution de tout litige découlant du présent Accord, les parties se soumettent à la juridiction des les juridictions compétentes désignées par la législation applicable.
                    </p>
                    {" "}
                    <p className="block mb-[0.9rem]">
                      Les présentes Conditions Générales ont été rédigées dans le but de protéger tant HOJA ACADEMY que ses Affiliés, en garantissant un cadre d'action transparent, licite et conforme à la réglementation en vigueur en Espagne et dans l'Union européenne.
                    </p>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </main>
      {" "}
      <Footer />
      {" "}
      <span className="w-1 h-1 border-2 border-inset border-foreground block absolute -top-[624.9375rem] overflow-clip" data-ditto-id="style-link-10" aria-hidden="true" role="presentation" title="Vidéo témoignage — apprenant HOJA ACADEMY"></span>
      {" "}
      <svg className="hidden overflow-hidden" data-ditto-id="style-not-started" fill="currentColor" />
      {" "}
          </>
  );
}
