import "./ditto.css";
import Footer from "../sections/footer";
import Navbar from "../sections/navbar";
import DittoWire from "../ditto/DittoWire";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import ListRow3 from "./components/list-row3";
import ListRow4 from "./components/list-row4";
import ListRow5 from "./components/list-row5";
import ListRow6 from "./components/list-row6";
import ListRow7 from "./components/list-row7";
import ListRow8 from "./components/list-row8";
import { ContactForm } from "../components/mailto-forms";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { href: "/formations/expert-ia", label: "Expert IA" },
    { href: "/formations/automatisation-n8n", label: "Automatisation & n8n" },
    { href: "/formations/robotique", label: "Robotique" },
    { href: "/formations/ia-recherche-sciences", label: "IA, Recherche & Sciences" }
];
const ListRow2_data = [
    { href: "/entreprises", label: "Entreprises" },
    { href: "/actualites", label: "Actualités" },
    { href: "/contact", label: "Contact" }
];
const ListRow3_data = [
    { href: "/entreprises", label: "Entreprises" },
    { href: "/actualites", label: "Actualités" },
    { href: "/contact", label: "Contact" }
];
const ListRow4_data = [
    { href: "/entreprises", label: "Entreprises" },
    { href: "/actualites", label: "Actualités" },
    { href: "/contact", label: "Contact" }
];
const ListRow_data2 = [
    { href: "/formations/expert-ia", label: "Expert IA" },
    { href: "/formations/automatisation-n8n", label: "Automatisation & n8n" },
    { href: "/formations/robotique", label: "Robotique" },
    { href: "/formations/ia-recherche-sciences", label: "IA, Recherche & Sciences" }
];
const ListRow5_data = [
    { href: "/entreprises", label: "Entreprises" }
];
const ListRow6_data = [
    { href: "https://wa.me/243792369704", label: "WHATSAPP" },
    { href: "mailto:info@hoja-academy.com", label: "LINKEDIN" },
    { href: "https://hojanetwork.org", label: "HOJA NETWORK" },
    { href: "https://hojanetwork.org", label: "HOJA NETWORK" }
];
const ListRow7_data = [
    { href: "/confidentialite", label: "Politique de Confidentialité & Conditions" },
    { href: "/cookies", label: "Politique des Cookies" },
    { href: "/mentions-legales", label: "Mentions Légales" },
    { href: "/accessibilite", label: "Accessibilité" },
    { href: "/entreprises", label: "Entreprises" }
];
const ListRow8_data = [
    { href: "/confidentialite", label: "Politique de Confidentialité & Conditions" },
    { href: "/cookies", label: "Politique des Cookies" },
    { href: "/mentions-legales", label: "Mentions Légales" },
    { href: "/accessibilite", label: "Accessibilité" },
    { href: "/entreprises", label: "Entreprises" }
];
const ListRow_meta: string[][] = [
    ["interaction-sm-1767225603097025-2", "n22"],
    ["n23", "n24"],
    ["n25", "style-wp-submit"],
    ["n27", "n28"]
];
const ListRow2_meta: string[][] = [
    ["n29", "style-div"],
    ["style-div-18", "style-div-2"],
    ["style-div-19", "style-div-3"]
];
const ListRow3_meta: string[][] = [
    ["n56", "n57"],
    ["n58", "n59"],
    ["n60", "n61"]
];
const ListRow4_meta: string[][] = [
    ["n79", "n80"],
    ["n81", "n82"],
    ["n83", "n84"]
];
const ListRow_meta2: string[][] = [
    ["interaction-sm-17672256027865476-2", "n177"],
    ["n178", "style-p-2"],
    ["style-b-5", "n181"],
    ["style-ul", "interaction-li-3"]
];
const ListRow5_meta: string[][] = [
    ["style-b", "style-li-2"],
    ["interaction-b-2", "style-li"],
    ["style-b-3", "n189"]
];
const ListRow6_meta: string[][] = [
    ["n202", "n203", "interaction-b"],
    ["n205", "style-b-2", "interaction-li"],
    ["style-b-6", "style-li-5", "style-b-7"],
    ["style-li-4", "style-b-4", "n213"]
];
const ListRow7_meta: string[][] = [
    ["n238", "style-div-17"],
    ["style-image", "n241"],
    ["n242", "style-div-97"],
    ["n244", "style-div-27"],
    ["n246", "style-heading-2"]
];
const ListRow8_meta: string[][] = [
    ["style-menu-1-74a24f8", "n253"],
    ["n254", "n255"],
    ["n256", "style-div-99"],
    ["n258", "n259"],
    ["style-span-4", "style-icon-4"]
];
const ListRow_styles = [
    { className: "rounded-tl-[25px] rounded-tr-[25px]" },
    {  },
    {  },
    { className: "rounded-br-[25px] rounded-bl-[25px]" }
,
    { className: "" }];
const ListRow2_styles = [
    { className: "mx-[0.5px] 2xl:mx-[9.5px] after:right-[6.5625rem] 2xl:after:right-29.5" },
    { className: "mx-[0.5px] 2xl:mx-[9.5px] after:right-[6.0625rem] 2xl:after:right-[6.9375rem]" },
    { className: "ml-[0.5px] 2xl:ml-[9.5px] after:right-[5.0625rem] 2xl:after:right-[5.8125rem]" }
,
    { className: "" },
    { className: "" }];
const ListRow3_styles = [
    {  },
    {  },
    { className: "max-lg:rounded-br-[10px] max-lg:rounded-bl-[10px]" }
,
    { className: "" },
    { className: "" }];
const ListRow4_styles = [
    { className: "mx-[0.5px] 2xl:mx-[9.5px] after:right-[6.5625rem] 2xl:after:right-29.5" },
    { className: "mx-[0.5px] 2xl:mx-[9.5px] after:right-[6.0625rem] 2xl:after:right-[6.9375rem]" },
    { className: "ml-[0.5px] 2xl:ml-[9.5px] after:right-[5.0625rem] 2xl:after:right-[5.8125rem]" }
,
    { className: "" },
    { className: "" }];
const ListRow_styles2 = [
    { className: "rounded-tl-[15px] rounded-tr-[15px]" },
    {  },
    {  },
    { className: "rounded-br-[15px] rounded-bl-[15px]" }
,
    { className: "" }];
const ListRow5_styles = [
    { className: "mx-[17.5px] max-md:mx-[0.5625rem] 2xl:mx-[21.5px]" },
    { className: "mx-[17.5px] max-md:mx-[0.5625rem] 2xl:mx-[21.5px]" },
    { className: "ml-[17.5px] max-md:ml-[0.5625rem] 2xl:ml-[21.5px]" }
,
    { className: "" },
    { className: "" }];
const ListRow7_styles = [
    { className: "mr-[8.5px] 2xl:mr-[9.5px]" },
    { className: "mx-[8.5px] 2xl:mx-[9.5px]" },
    { className: "mx-[8.5px] 2xl:mx-[9.5px]" },
    { className: "mx-[8.5px] 2xl:mx-[9.5px]" },
    { className: "ml-[8.5px] 2xl:ml-[9.5px]" }
];
const ListRow8_styles = [
    { className: "mr-[8.5px] max-md:mr-[0.4375rem]" },
    { className: "mx-[8.5px] max-md:mx-[0.4375rem]" },
    { className: "mx-[8.5px] max-md:mx-[0.4375rem]" },
    { className: "mx-[8.5px] max-md:mx-[0.4375rem]" },
    { className: "ml-[8.5px] max-md:ml-[0.4375rem]" }
];

export const metadata = {
  title: 'Contact | HOJA ACADEMY',
  description: "Parlons de votre projet : formations, candidatures, équipes, entreprises, institutions et recherche — par WhatsApp, téléphone ou e-mail.",
};
export default function Page() {
  return (
    <>
      {" "}
      <a className="w-px h-px block absolute -top-37500 left-0 -m-px overflow-hidden text-color-001 [font-family:Montserrat,_sans-serif] text-[0.9375rem] font-medium leading-[1.1875rem] [clip-path:inset(50%)] cursor-pointer" href="#content">
        Aller au contenu
      </a>
      {" "}
      <Navbar />
      {" "}
      <main className="block" id="content">
        {" "}
        <div className="block">
          <div className="block">
            <div className="min-h-100.5 flex relative max-w-full -mt-[7.0625rem] flex-col overflow-hidden bg-cover [background-position:50%_50%] bg-no-repeat 2xl:min-h-161.5" style={{ backgroundImage: "url(\"/assets/cloned/images/ed05935549e6.webp\")" }}>
              <div className="w-full flex max-w-[min(100%,_1140px)] mx-17.5 grow gap-5 max-md:max-w-[min(100%,_767px)] max-md:flex-wrap max-lg:mx-0 md:max-lg:max-w-[min(100%,_1024px)] 2xl:mx-97.5">
                <div className="w-full min-h-89.5 flex relative min-w-0 pt-12.5 flex-col justify-center max-lg:min-h-88.5 max-md:flex-wrap 2xl:min-h-108">
                  <div className="flex relative min-w-0 justify-center items-center gap-5 max-md:flex-wrap max-md:gap-x-[0.4375rem] max-md:gap-y-[initial]">
                    <div className="block relative min-w-0 max-w-full self-center gap-5 max-md:gap-x-[0.4375rem] max-md:gap-y-[initial]" data-ditto-id="style-span-39">
                      <div className="block pt-2.5" data-ditto-id="style-section">
                        <div className="block 2xl:text-end" data-ditto-id="style-div-83">
                          <div className="inline-block text-color-001 text-[3.0625rem] leading-[3.0625rem] text-center" data-ditto-id="style-p-10">
                            {" "}
                            <svg className="w-[3.0625rem] h-[3.0625rem] block relative overflow-hidden" data-ditto-id="style-heading-4" data-component="image" height="31" viewBox="0 0 69 31" width="69" xmlns="http://www.w3.org/2000/svg" fill="currentColor">
                              <g id="Grupo_241" data-name="Grupo 241" transform="translate(-251 -1259)">
                                <path id="Vector_168" data-name="Vector 168" d="M20.165,0l3.112,3.13L20.165,6.26m3.112-3.13H0" transform="translate(283 1271.37)" fill="none" stroke="#fff" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1" style={{ isolation: "isolate" }} />
                                <g id="Rectángulo_144" data-name="Rectángulo 144" transform="translate(251 1259)" fill="none" stroke="#fff" strokeWidth="1">
                                  <rect width="69" height="31" rx="15.5" stroke="none" />
                                  <rect x="0.5" y="0.5" width="68" height="30" rx="15" fill="none" />
                                </g>
                              </g>
                            </svg>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <div className="w-[27%] block relative min-w-0 max-w-full gap-5 max-md:w-[61.5%] max-md:gap-x-[0.4375rem] max-md:gap-y-[initial] md:max-lg:w-[35.5%] 2xl:w-[34%]" data-ditto-id="style-div-84">
                      <div className="block" data-ditto-id="style-span-40">
                        <h3 className="block text-primary text-[1.1875rem] leading-5 uppercase max-md:text-[1rem] 2xl:text-[1.625rem]" data-component="heading">
                          {"Vous avez une question ? "}
                        </h3>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                  <div className="block relative min-w-0 max-w-full text-center" data-ditto-id="interaction-span-11">
                    <div className="block">
                      <h2 className="block text-background [font-family:Montserrat,_sans-serif] text-[3.4375rem] leading-22 max-md:text-3xl max-md:leading-9 2xl:text-[5rem] 2xl:leading-[6.3125rem]" data-ditto-id="style-section-2" data-component="heading">
                        Parlons de votre projet.
                      </h2>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
            <div className="min-h-screen flex relative max-w-full flex-col shrink-0 overflow-hidden bg-color-001 bg-cover [background-position:50%_50%] bg-no-repeat max-md:px-5 max-md:flex-wrap" style={{ backgroundImage: "url(\"/assets/cloned/images/169bbdf891b7.webp\")" }} data-ditto-id="interaction-div-26">
              <div className="w-full min-h-78 flex relative min-w-0 max-md:min-h-[316.7px] max-md:flex-wrap md:max-lg:min-h-[24.9625rem] 2xl:min-h-[26.325rem]">
                <div className="w-[34.45rem] flex relative min-w-0 pt-26.5 pb-[2.1875rem] px-[2.1875rem] flex-col items-start gap-5 max-md:w-[20.9375rem] max-md:pt-12.5 max-md:flex-wrap max-lg:pb-0 max-md:px-0 md:max-lg:w-[322.5px] md:max-lg:pr-0 2xl:w-[51.5875rem]">
                  <div className="w-full flex relative min-w-0 p-2.5 items-center gap-x-9 max-md:flex-wrap max-lg:justify-center max-md:items-start max-lg:gap-x-3 max-lg:p-0 md:max-lg:w-82.5 2xl:gap-5" data-ditto-id="style-p-6">
                    <div className="w-[7.5%] block relative min-w-0 max-w-full self-center gap-x-9 max-md:w-[16%] max-lg:gap-x-3 md:max-lg:w-[14.5%] 2xl:w-[6%] 2xl:gap-5">
                      <div className="block pt-[0.1875rem]" data-ditto-id="style-p-13">
                        <div className="block" data-ditto-id="style-p-7">
                          <div className="inline-block text-color-001 text-[3.0625rem] leading-[3.0625rem] text-center">
                            {" "}
                            <svg className="w-[3.0625rem] h-[3.0625rem] block relative overflow-hidden" data-ditto-id="style-div-101" data-component="image" height="23.665" viewBox="0 0 52.673 23.665" width="52.673" xmlns="http://www.w3.org/2000/svg" fill="currentColor">
                              <g id="mark_deac" data-name="mark deac" transform="translate(-251 -1259)">
                                <path id="Vector_168" data-name="Vector 168" d="M15.393,0l2.376,2.39-2.376,2.39m2.376-2.39H0" transform="translate(275.428 1268.443)" fill="none" stroke="#41ffc1" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1" style={{ mixBlendMode: "normal", isolation: "isolate" }} />
                                <g id="Rectángulo_144" data-name="Rectángulo 144" transform="translate(251 1259)" fill="none" stroke="#41ffc1" strokeWidth="1">
                                  <rect width="52.673" height="23.665" rx="11.832" stroke="none" />
                                  <rect x="0.5" y="0.5" width="51.673" height="22.665" rx="11.332" fill="none" />
                                </g>
                              </g>
                            </svg>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <div className="w-[84.5%] block relative min-w-0 max-w-full gap-x-9 max-md:w-[70.5%] max-lg:gap-x-3 md:max-lg:w-[82%] 2xl:w-[91%] 2xl:gap-5">
                      <div className="block 2xl:-mt-[0.4375rem]">
                        <h3 className="block text-background text-[1.1875rem] leading-6 max-md:text-[0.9375rem] max-md:leading-[1.4375rem] md:max-lg:text-[1rem] 2xl:text-[1.625rem] 2xl:leading-7.5" data-component="heading">
                          Réponse directe
                        </h3>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                  <div className="w-full min-h-[14.5625rem] flex relative z-4 min-w-0 p-2.5 flex-col justify-between gap-5 max-md:min-h-[11.8125rem] max-md:flex-wrap max-lg:p-0">
                    <div className="w-full block relative min-w-0 max-w-full gap-5 max-md:text-center 2xl:w-[95%]" data-ditto-id="style-p-14">
                      <div className="block">
                        <h2 className="block text-background [font-family:Montserrat,_sans-serif] text-[2.1875rem] leading-[3.3125rem] max-md:text-[1.5625rem] max-md:leading-[2.375rem] md:max-lg:text-3xl md:max-lg:leading-[2.8125rem] 2xl:text-[2.8125rem] 2xl:leading-16.5" data-ditto-id="style-p-11" data-component="heading">
                          <span className="inline text-primary font-bold" data-ditto-id="style-p-8">
                            {" Parlons de votre projet "}
                          </span>
                          — écrivez-nous par WhatsApp, téléphone ou e-mail
                        </h2>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
                <div className="w-full flex relative min-w-0 pt-30 pb-10 px-10 flex-col justify-start items-end gap-5 max-md:min-h-[14.3125rem] max-md:flex-wrap max-md:justify-center max-md:p-0" data-ditto-id="style-p-9">
                  <div className="w-[87%] h-full min-h-[20.8125rem] border border-solid border-foreground flex relative min-w-0 p-18 rounded-[38px] flex-col justify-center gap-y-[1.1875rem] bg-surface-9 [backdrop-filter:blur(6.4px)] max-md:w-full max-md:min-h-[18.0625rem] max-lg:p-7.5 max-md:flex-wrap 2xl:min-h-[18.9375rem]" data-ditto-id="interaction-p" id="containerFormacion">
                    <div className="block relative min-w-0 max-w-full gap-y-[1.1875rem]" data-ditto-id="style-p-12">
                      <div className="block" data-ditto-id="style-p-4">
                        <h2 className="block text-background text-[1.6875rem] font-bold uppercase max-md:leading-7.5 max-md:[font-size:inherit] 2xl:leading-5" data-ditto-id="interaction-p-2" data-component="heading">
                          Nous écrire
                        </h2>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <div className="w-full block relative min-w-0 max-w-full gap-y-[1.1875rem] text-background text-[1.125rem] leading-[2rem] max-md:text-base max-lg:leading-7.5 md:max-lg:text-lg 2xl:w-[84%]" data-ditto-id="interaction-p-3">
                      <div className="h-full block" data-ditto-id="interaction-button">
                        <p className="block mb-[0.9rem]">
                          <a className="inline-block py-3 px-6 rounded-[33px] text-color-001 [font-family:Montserrat,_sans-serif] text-[0.9375rem] font-semibold text-center bg-primary cursor-pointer" data-component="link" href="https://wa.me/243792369704" target="_blank" rel="noopener">WhatsApp</a>
                        </p>
                        <p className="block mb-[0.9rem]">
                          {"Téléphone / WhatsApp : "}
                          <span className="inline underline">
                            <a className="inline [font-family:Montserrat,_sans-serif] text-[0.9375rem] font-medium leading-[1.1875rem] cursor-pointer" data-component="link" href="tel:+243792369704">
                              <strong className="inline font-bold">+243 792 369 704</strong>
                            </a>
                          </span>
                          {" (local : 0792369704)"}
                        </p>
                        <p className="block mb-[0.9rem]">
                          {"E-mail : "}
                          <span className="inline underline">
                            <a className="inline [font-family:Montserrat,_sans-serif] text-[0.9375rem] font-medium leading-[1.1875rem] cursor-pointer" data-component="link" href="mailto:info@hoja-academy.com">
                              <strong className="inline font-bold">info@hoja-academy.com</strong>
                            </a>
                          </span>
                        </p>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <div className="block relative min-w-0 max-w-full gap-y-[1.1875rem]">
                      <div className="block" data-ditto-id="style-br-2">
                        <h2 className="block text-background text-[1.6875rem] font-bold uppercase max-md:leading-7.5 max-md:[font-size:inherit] 2xl:leading-5" data-ditto-id="interaction-br" data-component="heading">
                          Pourquoi nous contacter
                        </h2>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <div className="w-full block relative min-w-0 max-w-full text-background text-[1.0625rem] leading-[1.9rem] max-md:text-base 2xl:w-[84%]">
                      <ul className="block [list-style-type:disc] pl-5 m-0">
                        <li>{"Une question sur les formations"}</li>
                        <li>{"Une candidature"}</li>
                        <li>{"Une formation pour une équipe"}</li>
                        <li>{"Un accompagnement d'entreprise"}</li>
                        <li>{"Un projet institutionnel"}</li>
                        <li>{"Un projet de recherche"}</li>
                        <li>{"Une collaboration"}</li>
                      </ul>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
          <div className="w-full max-w-[min(100%,_1140px)] mx-17.5 px-[2.1875rem] py-16 max-md:px-5 max-lg:mx-0 2xl:mx-97.5" id="formulaire-contact">
            <h2 className="block mb-2 text-color-001 [font-family:Montserrat,_sans-serif] text-[1.6875rem] font-bold uppercase">Formulaire de contact</h2>
            <p className="block mb-8 text-foreground text-[0.9375rem] leading-6">
              {"Remplissez les champs ci-dessous : votre messagerie s'ouvre avec un e-mail prérempli à destination de "}
              <a className="inline underline text-primary font-semibold cursor-pointer" href="mailto:info@hoja-academy.com">info@hoja-academy.com</a>
              {". Ce site ne dispose d'aucun serveur : rien n'est envoyé ni enregistré automatiquement."}
            </p>
            <ContactForm />
          </div>
          {" "}
        </div>
        {" "}
      </main>
      {" "}
      <Footer />
      {" "}
      <span className="w-1 h-1 border-2 border-inset border-foreground block absolute -top-[624.9375rem] overflow-clip" data-ditto-id="style-image-5" aria-hidden="true" role="presentation" title="Vidéo témoignage — apprenant HOJA ACADEMY"></span>
      {" "}
      <svg className="hidden overflow-hidden" data-ditto-id="style-iframe-2" fill="currentColor" />
      {" "} <div className="block" />
          </>
  );
}
