import "./ditto.css";
import Footer from "../sections/footer";
import Navbar from "../sections/navbar";
import DittoWire from "../ditto/DittoWire";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import ListRow3 from "./components/list-row3";
import ListRow4 from "./components/list-row4";
import ListRow5 from "./components/list-row5";
import ListRow6 from "./components/list-row6";
import ListRow7 from "./components/list-row7";
import ListRow8 from "./components/list-row8";
import ListRow9 from "./components/list-row9";
import ListRow10 from "./components/list-row10";
import ListRow11 from "./components/list-row11";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { href: "/formations/expert-ia", label: "Expert IA" },
    { href: "/formations/automatisation-n8n", label: "Automatisation & n8n" },
    { href: "/formations/robotique", label: "Robotique" },
    { href: "/formations/ia-recherche-sciences", label: "IA, Recherche & Sciences" }
];
const ListRow2_data = [
    { href: "/entreprises", label: "Entreprises" },
    { href: "/actualites", label: "Actualités" },
    { href: "/contact", label: "Contact" }
];
const ListRow3_data = [
    { href: "/entreprises", label: "Entreprises" },
    { href: "/actualites", label: "Actualités" },
    { href: "/contact", label: "Contact" }
];
const ListRow4_data = [
    { href: "/entreprises", label: "Entreprises" },
    { href: "/actualites", label: "Actualités" },
    { href: "/contact", label: "Contact" }
];
const ListRow5_data = [
    { text: "Cookies techniques :", text2: " permettent à l'utilisateur de naviguer sur un site web, une plateforme ou une application et d'utiliser les différentes options ou services qui y existent, par exemple : contrôler le trafic et la communication de données, identifier la session, accéder à des zones d'accès restreint, mémoriser les éléments d'une commande, réaliser le processus d'achat, effectuer une demande d'inscription ou de participation à un événement, utiliser des éléments de sécurité pendant la navigation, stocker du contenu pour la diffusion de vidéos ou d'audio, ou partager du contenu sur les réseaux sociaux." },
    { text: "Cookies de personnalisation :", text2: " permettent à l'utilisateur d'accéder au service avec certaines caractéristiques générales prédéfinies selon des critères du terminal de l'utilisateur, par exemple la langue, le type de navigateur utilisé pour accéder au service, la région configurée pour y accéder, etc." },
    { text: "Cookies analytiques :", text2: " permettent au responsable de leur suivi et de leur analyse d'observer le comportement des utilisateurs des sites web auxquels elles sont liées, y compris la quantification des impacts des annonces. Les informations collectées via ces cookies sont utilisées pour mesurer l'activité des sites web, applications ou plateformes, afin d'introduire des améliorations basées sur l'analyse des données d'utilisation des utilisateurs du service." },
    { text: "Cookies publicité comportementale :", text2: " stockent des informations sur le comportement des utilisateurs obtenues par observation continue de leurs habitudes de navigation, ce qui permet d'élaborer un profil spécifique pour afficher une publicité adaptée." }
];
const ListRow6_data = [
    { text: "wordpress_sec_[hash]:", text2: " Identique au précédent. ", text3: "Nécessaire" },
    { text: "wordpress_logged_in_[hash]: ", text2: " Enregistre votre identité pendant votre session et est utilisé par WordPress pour son interface. ", text3: "Technique de session. Nécessaire" },
    { text: "wp-postpass_[hash]", text2: " : Cookie conservant l'accès aux pages protégées par mot de passe. ", text3: "Technique persistante. Durée par défaut 10 jours" }
];
const ListRow5_data2 = [
    { text: "_ga:", text2: " Analytique Google. Utilisé pour distinguer les utilisateurs (expire dans 2 ans)." },
    { text: "_gid:", text2: " Utilisé pour distinguer les utilisateurs (expire dans 24 heures)." },
    { text: "_gat:", text2: " Se usa para limitar el porcentaje de solicitudes (expira en 1 minuto)." }
];
const ListRow7_data = [
    { text: "Firefox: ", href: "https://support.mozilla.org/en-US/kb/cookies-information-websites-store-on-your-computer", label: "https://support.mozilla.org/en-US/kb/cookies-information-websites-store-on-your-computer" },
    { text: "Chrome: ", href: "https://support.google.com/chrome/bin/answer.py?hl=en&answer=95647&topic=14666&ctx=topic", label: "https://support.google.com/chrome/bin/answer.py?hl=en&answer=95647&topic=14666&ctx=topic" },
    { text: "Internet Explorer 8-10: ", href: "https://windows.microsoft.com/en-US/internet-explorer/delete-manage-cookies", label: "https://windows.microsoft.com/en-US/internet-explorer/delete-manage-cookies" },
    { text: "Safari: ", href: "https://support.apple.com/kb/ph5042", label: "https://support.apple.com/kb/ph5042" },
    { text: "Opera: ", href: "https://help.opera.com/Windows/12.00/es-ES/cookies.html", label: "https://help.opera.com/Windows/12.00/es-ES/cookies.html" }
];
const ListRow_data2 = [
    { href: "/formations/expert-ia", label: "Expert IA" },
    { href: "/formations/automatisation-n8n", label: "Automatisation & n8n" },
    { href: "/formations/robotique", label: "Robotique" },
    { href: "/formations/ia-recherche-sciences", label: "IA, Recherche & Sciences" }
];
const ListRow8_data = [
    { href: "/entreprises", label: "Entreprises" }
];
const ListRow9_data = [
    { href: "https://wa.me/243792369704", label: "WHATSAPP" },
    { href: "mailto:info@hoja-academy.com", label: "LINKEDIN" },
    { href: "https://hojanetwork.org", label: "HOJA NETWORK" },
    { href: "https://hojanetwork.org", label: "HOJA NETWORK" }
];
const ListRow10_data = [
    { href: "/confidentialite", label: "Politique de Confidentialité & Conditions" },
    { href: "/cookies", ariacurrent: "page", label: "Politique des Cookies" },
    { href: "/mentions-legales", label: "Mentions Légales" },
    { href: "/accessibilite", label: "Accessibilité" },
    { href: "/entreprises", label: "Entreprises" }
];
const ListRow11_data = [
    { href: "/confidentialite", label: "Politique de Confidentialité & Conditions" },
    { href: "/cookies", ariacurrent: "page", label: "Politique des Cookies" },
    { href: "/mentions-legales", label: "Mentions Légales" },
    { href: "/accessibilite", label: "Accessibilité" },
    { href: "/entreprises", label: "Entreprises" }
];
const ListRow_meta: string[][] = [
    ["n22", "n23"],
    ["n24", "n25"],
    ["style-wp-submit", "n27"],
    ["n28", "n29"]
];
const ListRow2_meta: string[][] = [
    ["style-div", "style-div-18"],
    ["style-div-2", "style-div-19"],
    ["style-div-3", "style-div-20"]
];
const ListRow3_meta: string[][] = [
    ["n57", "n58"],
    ["n59", "n60"],
    ["n61", "n62"]
];
const ListRow4_meta: string[][] = [
    ["n80", "n81"],
    ["n82", "n83"],
    ["n84", "n85"]
];
const ListRow5_meta: string[][] = [
    ["style-p-8", "style-p-9"],
    ["interaction-p", "style-p-12"],
    ["style-p-4", "interaction-p-2"],
    ["interaction-p-3", "interaction-button"]
];
const ListRow6_meta: string[][] = [
    ["n153", "style-br", "interaction-span"],
    ["n156", "n157", "style-span-47"],
    ["n159", "n160", "style-p-15"]
];
const ListRow5_meta2: string[][] = [
    ["interaction-div-6", "interaction-div-8"],
    ["style-menu-2", "interaction-menu-1-516d334"],
    ["n170", "style-link-32"]
];
const ListRow7_meta: string[][] = [
    ["style-b-3", "n189", "n190", "interaction-div-5"],
    ["interaction-div-3", "style-div-16", "style-div-15", "interaction-div-4"],
    ["n196", "style-link-5", "n198", "n199"],
    ["style-div-10", "style-div-94", "n202", "n203"],
    ["interaction-b", "n205", "style-b-2", "interaction-li"]
];
const ListRow_meta2: string[][] = [
    ["style-div-103", "style-div-5"],
    ["style-div-6", "style-menu"],
    ["n238", "style-div-17"],
    ["style-image", "n241"]
];
const ListRow8_meta: string[][] = [
    ["n242", "style-div-97"],
    ["n244", "style-div-27"],
    ["n246", "style-heading-2"]
];
const ListRow9_meta: string[][] = [
    ["style-span-4", "style-icon-4", "style-div-11"],
    ["style-div-21", "style-div-100", "style-div-13"],
    ["n266", "n267", "style-gt-wrapper-56609209"],
    ["style-english", "style-spanish", "n271"]
];
const ListRow10_meta: string[][] = [
    ["style-div-39", "n297"],
    ["n298", "style-gt-wrapper-28246617"],
    ["style-div-8", "style-div-9"],
    ["style-menu-3", "n303"],
    ["style-div-41", "style-image-4"]
];
const ListRow11_meta: string[][] = [
    ["style-iframe", "n311"],
    ["n312", "style-brevo-conversations"],
    ["style-div-12", "n315"],
    ["n316", "n317"],
    ["style-div-25", "interaction-gt-wrapper-30105788"]
];
const ListRow_styles = [
    { className: "rounded-tl-[25px] rounded-tr-[25px]" },
    {  },
    {  },
    { className: "rounded-br-[25px] rounded-bl-[25px]" }
,
    { className: "" }];
const ListRow2_styles = [
    { className: "mx-[0.5px] 2xl:mx-[9.5px] after:right-[6.5625rem] 2xl:after:right-29.5" },
    { className: "mx-[0.5px] 2xl:mx-[9.5px] after:right-[6.0625rem] 2xl:after:right-[6.9375rem]" },
    { className: "ml-[0.5px] 2xl:ml-[9.5px] after:right-[5.0625rem] 2xl:after:right-[5.8125rem]" }
,
    { className: "" },
    { className: "" }];
const ListRow3_styles = [
    {  },
    {  },
    { className: "max-lg:rounded-br-[10px] max-lg:rounded-bl-[10px]" }
,
    { className: "" },
    { className: "" }];
const ListRow4_styles = [
    { className: "mx-[0.5px] 2xl:mx-[9.5px] after:right-[6.5625rem] 2xl:after:right-29.5" },
    { className: "mx-[0.5px] 2xl:mx-[9.5px] after:right-[6.0625rem] 2xl:after:right-[6.9375rem]" },
    { className: "ml-[0.5px] 2xl:ml-[9.5px] after:right-[5.0625rem] 2xl:after:right-[5.8125rem]" }
,
    { className: "" },
    { className: "" }];
const ListRow_styles2 = [
    { className: "rounded-tl-[15px] rounded-tr-[15px]" },
    {  },
    {  },
    { className: "rounded-br-[15px] rounded-bl-[15px]" }
,
    { className: "" }];
const ListRow8_styles = [
    { className: "mx-[17.5px] max-md:mx-[0.5625rem] 2xl:mx-[21.5px]" },
    { className: "mx-[17.5px] max-md:mx-[0.5625rem] 2xl:mx-[21.5px]" },
    { className: "ml-[17.5px] max-md:ml-[0.5625rem] 2xl:ml-[21.5px]" }
,
    { className: "" },
    { className: "" }];
const ListRow10_styles = [
    { className: "mr-[8.5px] 2xl:mr-[9.5px]" },
    { className: "mx-[8.5px] 2xl:mx-[9.5px]" },
    { className: "mx-[8.5px] 2xl:mx-[9.5px]" },
    { className: "mx-[8.5px] 2xl:mx-[9.5px]" },
    { className: "ml-[8.5px] 2xl:ml-[9.5px]" }
];
const ListRow11_styles = [
    { className: "mr-[8.5px] max-md:mr-[0.4375rem]" },
    { className: "mx-[8.5px] max-md:mx-[0.4375rem]" },
    { className: "mx-[8.5px] max-md:mx-[0.4375rem]" },
    { className: "mx-[8.5px] max-md:mx-[0.4375rem]" },
    { className: "ml-[8.5px] max-md:ml-[0.4375rem]" }
];

export const metadata = {
  title: 'Politique des cookies | HOJA ACADEMY',
  description: 'Gestion des cookies sur hoja-academy.com : types, finalités et configuration.',
};
export default function Page() {
  return (
    <>
      {" "}
      <span className="w-1 h-1 border-2 border-inset border-foreground block absolute -top-[624.9375rem] overflow-clip" aria-hidden="true" role="presentation" title="Vidéo témoignage — apprenant HOJA ACADEMY"></span>
      {" "}
      <a className="w-px h-px block absolute -top-37500 left-0 -m-px overflow-hidden text-color-001 [font-family:Montserrat,_sans-serif] text-[0.9375rem] font-medium leading-[1.1875rem] [clip-path:inset(50%)] cursor-pointer" href="#content">
        Aller au contenu
      </a>
      {" "}
      <Navbar />
      {" "}
      <main className="block" id="content">
        {" "}
        <div className="block">
          <div className="block">
            <div className="min-h-[25.3125rem] flex relative max-w-full -mt-[7.0625rem] justify-center items-center gap-5 bg-color-001 bg-cover [background-position:50%_50%] bg-no-repeat max-md:min-h-[15.0625rem] max-md:-mt-22.5 max-md:px-[0.9375rem] max-md:flex-wrap max-md:justify-end md:max-lg:px-[3.3125rem] 2xl:-mt-33 2xl:pl-[13.8125rem]" style={{ backgroundImage: "url(\"/assets/cloned/images/6bfaf6f6a88b.png\")" }}>
              <div className="w-240 min-h-[16.3125rem] flex relative min-w-0 flex-col justify-end gap-5 max-md:w-[21.5625rem] max-md:min-h-41 max-md:flex-wrap md:max-lg:w-[569.3px] 2xl:w-[106.1875rem] 2xl:p-2.5">
                <div className="block relative min-w-0 max-w-full gap-5">
                  <div className="block" data-ditto-id="style-span-39">
                    <h1 className="block text-primary [font-family:Montserrat,_sans-serif] text-[2.625rem] font-bold leading-[6.3125rem] max-md:text-3xl max-md:leading-9 md:max-lg:leading-[3.125rem]" data-ditto-id="style-section" data-component="heading">
                      Politique des Cookies
                    </h1>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
            <div className="min-h-[44.8125rem] flex relative max-w-full py-16 px-[3.2rem] justify-center gap-5 max-md:pt-10 max-md:pb-5 max-md:px-5 max-md:flex-wrap md:max-lg:py-[2.4rem] md:max-lg:px-[30.7px] 2xl:py-24 2xl:px-[4.8rem]" data-ditto-id="style-div-83">
              <div className="w-4/5 block relative min-w-0 max-w-full gap-5 text-color-001 max-md:text-base max-md:leading-[1.3125rem]" data-ditto-id="style-p-10">
                <div className="h-full block" data-ditto-id="style-heading-4">
                  <p className="block mb-[0.9rem]" data-ditto-id="style-div-84">
                    <b className="inline font-bold" data-ditto-id="style-span-40">
                      Que sont les cookies ?
                    </b>
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]">
                    Les cookies sont de petits fichiers texte stockés sur l'appareil de l'utilisateur lors de la visite d'un site web. C'est l'opérateur du site qui détermine le type d'informations contenues dans le cookie et son objectif, celui-ci pouvant en outre être utilisé par le serveur web à chaque visite de la page. Les cookies servent à gagner du temps et à rendre l'expérience de navigation bien plus efficace. Ils peuvent néanmoins avoir des finalités variées, par exemple mémoriser les informations de connexion ou le contenu de votre panier d'achat.
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="interaction-span-11">
                    <b className="inline font-bold">
                      Types de cookies selon l'entité qui les gère :
                    </b>
                  </p>
                  {" "}
                  <ul className="block pl-10 [list-style-type:disc] list-outside" data-ditto-id="style-section-2">
                    <li className="list-item" data-ditto-id="interaction-div-26">
                      <b className="inline font-bold">
                        Cookies propias:
                      </b>
                      {" ce sont celles qui sont envoyées à l'équipement terminal de l'utilisateur depuis un autre équipement ou domaine géré par l'éditeur lui-même et à partir duquel est fourni le service demandé par ledit utilisateur."}
                    </li>
                    <li className="list-item">
                      <b className="inline font-bold" data-ditto-id="style-p-6">
                        Cookies tiers
                      </b>
                      : ce sont celles qui sont envoyées à l'équipement terminal de l'utilisateur depuis un autre équipement ou domaine géré non par l'éditeur, mais par une autre entité qui traite les données obtenues par le biais des cookies.
                    </li>
                  </ul>
                  {" "}
                  <p className="block mb-[0.9rem]">
                    <b className="inline font-bold" data-ditto-id="style-p-13">
                      <br className="inline" data-ditto-id="style-p-7" />
                      {" Types de cookies selon la durée pendant laquelle ils restent activés :"}
                    </b>
                  </p>
                  {" "}
                  <ul className="block pl-10 [list-style-type:disc] list-outside">
                    <li className="list-item" data-ditto-id="style-div-101">
                      <b className="inline font-bold">
                        Cookies de session :
                      </b>
                      {" sont un type de cookies conçus pour recueillir et stocker des données pendant que l'utilisateur accède à une page web."}
                    </li>
                    <li className="list-item">
                      <b className="inline font-bold">
                        Cookies persistants :
                      </b>
                      {" sont un type de cookies où les données restent stockées sur le terminal et peuvent être consultées et traitées pendant une période définie par le responsable du cookie, pouvant aller de quelques minutes à plusieurs années."}
                    </li>
                  </ul>
                  {" "}
                  <p className="block mb-[0.9rem]">
                    <b className="inline font-bold" data-ditto-id="style-p-14">
                      <br className="inline" />
                      {" Types de cookies selon leur finalité :"}
                    </b>
                  </p>
                  {" "}
                  <ul className="block pl-10 [list-style-type:disc] list-outside" data-ditto-id="style-p-11">
                    {ListRow5_data.map((d, i) => <ListRow5 key={i} d={d} />)}
                  </ul>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="interaction-span-3">
                    <b className="inline font-bold" data-ditto-id="style-p">
                      <br className="inline" data-ditto-id="interaction-link" />
                      {" Quels cookies utilisons-nous chez HOJA ACADEMY ?"}
                    </b>
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="interaction-span-4">
                    <b className="inline font-bold" data-ditto-id="style-navegaci-n-entre-noticias-del-d-a">
                      Cookies techniques :
                    </b>
                  </p>
                  {" "}
                  <ul className="block pl-10 [list-style-type:disc] list-outside" data-ditto-id="style-link-7">
                    <li className="list-item" data-ditto-id="style-br-3">
                      <b className="inline font-bold">
                        moove_gdpr_popup
                      </b>
                      : Permet de déterminer si l'avis cookies doit s'afficher ou non (s'il a déjà été accepté ou refusé, il ne s'affiche plus tant que ce cookie persiste). Expire au bout de 1 an.
                    </li>
                    <li className="list-item">
                      <b className="inline font-bold">
                        cpnb_cookiesSettings
                      </b>
                      : Permet de vérifier quelles catégories de cookies sont acceptées ou refusées (par exemple, cookies analytiques, cookies de publicité ciblée, etc.). Expire au bout de 1 an.
                    </li>
                    <li className="list-item">
                      <b className="inline font-bold" data-ditto-id="style-br-2">
                        wordpress_[hash]:
                      </b>
                      {" Cookie restreint à la zone d'administration (wp-admin). Il n'apparaît pas sur le frontend, même lorsque vous êtes inscrit. Il conserve vos données de connexion. "}
                      <b className="inline font-bold" data-ditto-id="interaction-br">
                        Technique de session. Nécessaire.
                      </b>
                    </li>
                    {ListRow6_data.map((d, i) => <ListRow6 key={i} d={d} meta={ListRow6_meta[i]} />)}
                  </ul>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-footer-3">
                    <b className="inline font-bold">
                      Cookies analytiques :
                    </b>
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="interaction-div-7">
                    Qu'elles soient traitées par nous-mêmes ou par des tiers, elles nous permettent de quantifier le nombre d'utilisateurs et d'effectuer la mesure et l'analyse statistique de l'utilisation qui est faite du service proposé. À cette fin, nous analysons votre navigation sur notre site web afin d'améliorer l'offre de produits ou de services que nous vous proposons.
                  </p>
                  {" "}
                  <ul className="block pl-10 [list-style-type:disc] list-outside">
                    {ListRow5_data2.map((d, i) => <ListRow5 key={i} d={d} />)}
                  </ul>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="interaction-li-2">
                    {"Plus d'informations sur ces cookies sur "}
                    <a className="inline text-accent [font-family:Montserrat,_sans-serif] text-[0.9375rem] font-medium leading-[1.1875rem] cursor-pointer" data-ditto-id="interaction-sm-17672256027865476-1" data-component="link" href="https://www.google.es/analytics/terms/es.html">
                      <span className="inline" data-ditto-id="style-span-6">
                        Google Analytics
                      </span>
                    </a>
                    .
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-icon-2">
                    <b className="inline font-bold" data-ditto-id="interaction-sm-17672256027865476-2">
                      Cookies publicitaires et de réseaux sociaux :
                    </b>
                  </p>
                  {" "}
                  <ul className="block pl-10 [list-style-type:disc] list-outside">
                    <li className="list-item">
                      <b className="inline font-bold" data-ditto-id="style-p-2">
                        {"_fbq: "}
                      </b>
                      Utilisé par le pixel de Facebook pour effectuer le suivi de la visite. Expire au bout de 3 mois.
                    </li>
                  </ul>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-b-5">
                    <b className="inline font-bold">
                      <br className="inline" data-ditto-id="style-ul" />
                      {" Révocation du consentement d'utilisation des Cookies :"}
                    </b>
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="interaction-li-3">
                    Si vous souhaitez révoquer ou reconfigurer votre consentement, vous disposez d'un bouton flottant permanent situé en bas à droite de l'écran, donnant accès aux paramètres des cookies.
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-b">
                    <b className="inline font-bold" data-ditto-id="style-li-2">
                      Comment les cookies sont-ils gérés ?
                    </b>
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="interaction-b-2">
                    Les cookies étant de simples fichiers texte, vous pouvez les consulter avec la plupart des éditeurs de texte ou traitements de texte. Vous pouvez cliquer sur un cookie pour l'ouvrir. Vous trouverez ci-après une liste de liens expliquant comment consulter les cookies dans différents navigateurs. Si vous utilisez un autre navigateur, consultez les informations relatives aux cookies dans celui-ci. Si vous utilisez un téléphone mobile, consultez le manuel de l'appareil pour plus d'informations.
                  </p>
                  {" "}
                  <ul className="block pl-10 [list-style-type:disc] list-outside" data-ditto-id="style-li">
                    {ListRow7_data.map((d, i) => <ListRow7 key={i} d={d} />)}
                  </ul>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-b-6">
                    <b className="inline font-bold" data-ditto-id="style-li-5">
                      <br className="inline" data-ditto-id="style-b-7" />
                      {" Désactivation/activation ou suppression des cookies :"}
                    </b>
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-li-4">
                    Pour restreindre ou bloquer les cookies, cela se fait par le biais de la configuration du navigateur.
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-b-4">
                    Si vous ne souhaitez pas que des sites web déposent des cookies sur votre appareil, vous pouvez configurer votre navigateur pour être averti avant qu'un cookie soit déposé. De même, vous pouvez configurer le navigateur pour qu'il refuse tous les cookies, ou uniquement les cookies tiers. Vous pouvez également supprimer les cookies déjà présents sur votre appareil. Notez que vous devrez configurer séparément chaque navigateur et appareil que vous utilisez.
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]">
                    Notez que si vous ne souhaitez pas recevoir de cookies, nous ne pourrons plus garantir le bon fonctionnement de notre site web. Certaines fonctions du site peuvent être perdues et vous pourriez ne plus pouvoir consulter certains sites. Refuser les cookies ne signifie pas que vous ne verrez plus de publicités ; celles-ci ne seront simplement pas adaptées à vos intérêts et se répéteront plus fréquemment.
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-footer">
                    Chaque navigateur dispose d'une méthode différente pour adapter la configuration. Si nécessaire, consultez la fonction d'aide du navigateur pour définir la configuration correcte.
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-div-95">
                    Pour désactiver les cookies sur le téléphone mobile, consultez le manuel de l'appareil pour obtenir plus d'informations.
                  </p>
                  {" "}
                  <p className="block mb-[0.9rem]">
                    {"Vous pouvez obtenir plus d'informations sur les cookies sur Internet, "}
                    <a className="inline [font-family:Montserrat,_sans-serif] text-[0.9375rem] font-medium leading-[1.1875rem] cursor-pointer" data-ditto-id="interaction-div-2" data-component="link" href="https://www.aboutcookies.org/">
                      <span className="inline" data-ditto-id="style-link-2">
                        https://www.aboutcookies.org
                      </span>
                    </a>
                    .
                  </p>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </main>
      {" "}
      <Footer />
      {" "}
      <svg className="hidden overflow-hidden" fill="currentColor" />
      {" "}
          </>
  );
}
